export default {
  '*': {
    theme: {
      sidebar: false,
      toc: true,
      pagination: false,
      typesetting: 'article',
      breadcrumb: false,
      timestamp: true,
    },
  },
  'introducing-koshmoney-countries': 'Introducing @koshmoney/countries',
  'iso-3166-country-codes-guide': 'ISO 3166 Country Codes: The Complete Guide',
  'react-country-dropdown-typescript': 'Build a Country Dropdown in React with TypeScript',
  'us-state-codes-list': 'US State Codes: Complete List with ISO 3166-2',
  'canadian-province-codes': 'Canadian Province and Territory Codes',
  'eu-country-codes-list': 'EU Country Codes: Complete List',
  'gdpr-eu-countries-developers': 'GDPR EU Countries for Developers',
  'tree-shaking-country-data': 'Tree-Shaking Country Data: From 60KB to 8KB',
  'international-shipping-zones-country-state': 'International Shipping Zones by Country and State',
  'best-country-npm-packages-2026': 'Best Country Code npm Packages in 2026',
  'iso-country-codes-kyc-compliance': 'ISO Country Codes for KYC Compliance',
  'nodejs-country-code-validation': 'Server-Side Country Code Validation in Node.js',
  'african-countries-list-codes': 'African Countries: Complete List with ISO Codes',
  'asian-countries-list-codes': 'Asian Countries: Complete List with ISO Codes',
  'european-countries-list-codes': 'European Countries: Complete List with ISO Codes',
  'south-american-countries-list-codes': 'South American Countries: Complete List with ISO Codes',
  'sepa-countries-list': 'SEPA Countries List: All 36 Members with ISO Codes',
  'north-american-countries-list-codes': 'North American Countries: Complete List with ISO Codes',
  'oceania-countries-list-codes': 'Oceania Countries: Complete List with ISO Codes',
  'eurozone-countries-list': 'Eurozone Countries List 2026: All 21 Members Using the Euro',
  'schengen-countries-list': 'Schengen Countries List: All 27 Members',
  'countries-using-us-dollar': '18 Countries Using the US Dollar (USD): Full 2026 List',
  'countries-using-euro': '35 Countries Using the Euro (EUR): Full 2026 List with ISO Codes',
  'international-dialing-codes-list': 'International Dialing Codes List: Every Country',
  'countries-sharing-dial-code': 'Countries Sharing the Same Dial Code (+1, +44, +7 and More)',
  'country-code-faq': 'Country Code FAQ: 25 Questions About ISO 3166 Codes Answered',
  'australian-state-codes-list': 'Australian State and Territory Codes: Complete List',
  'indian-state-codes-list': 'Indian State and Union Territory Codes: Complete List',
  'german-state-codes-list': 'German State Codes: Complete List of All 16 Bundeslaender',
  'uk-region-codes-list': 'UK Region Codes: Complete ISO 3166-2 Guide',
  'uk-country-codes-subdivisions': 'UK Country Codes & Subdivisions: Complete ISO 3166-2:GB Reference',
  'japanese-prefecture-codes-list': 'Japanese Prefecture Codes: Complete List of All 47 Prefectures',
  'brazilian-state-codes-list': 'Brazilian State Codes: Complete List of All 27 Subdivisions',
  'mexican-state-codes-list': 'Mexican State Codes: Complete List of All 32 Subdivisions',
  'french-region-codes-list': 'French Region and Department Codes: Complete ISO 3166-2 Guide',
  'italian-region-codes-list': 'Italian Region Codes: Complete ISO 3166-2 Guide',
  'spanish-community-codes-list': 'Spanish Autonomous Community Codes: All 19 ISO 3166-2:ES Regions',
  'chinese-province-codes-list': 'Chinese Province Codes: Complete ISO 3166-2:CN Reference',
  'country-code-formats-alpha2-alpha3-numeric': 'Country Code Formats Explained: Alpha-2 vs Alpha-3 vs Numeric',
  'all-249-country-codes-list': 'Complete List of All 249 ISO 3166 Country Codes',
  'south-korean-province-codes-list': 'South Korean Province Codes: Complete ISO 3166-2:KR Reference',
  'phone-country-codes-dial-codes': 'Phone Country Codes: Complete International Dial Code Reference',
  'eu-vs-eurozone-countries': 'EU Countries vs Eurozone Countries: What\'s the Difference?',
  'dollar-currencies-worldwide': 'Every Dollar Currency in the World: USD, AUD, CAD, and 20+ More',
  'ofac-sanctioned-countries-developers': 'OFAC Sanctioned Countries: A Developer\'s Guide to Sanctions Compliance',
  'stablecoin-supported-countries': 'Stablecoin Supported Countries 2026: Where USDC and USDT Work',
}
