// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AD';
export const countryName = "Andorra";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AD-02': { name: "Canillo", type: "Parish" },
  'AD-03': { name: "Encamp", type: "Parish" },
  'AD-04': { name: "La Massana", type: "Parish" },
  'AD-05': { name: "Ordino", type: "Parish" },
  'AD-06': { name: "Sant Julià de Lòria", type: "Parish" },
  'AD-07': { name: "Andorra la Vella", type: "Parish" },
  'AD-08': { name: "Escaldes-Engordany", type: "Parish" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
