// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AE';
export const countryName = "United Arab Emirates";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AE-AJ': { name: "'Ajmān", type: "Emirate" },
  'AE-AZ': { name: "Abū Z̧aby", type: "Emirate" },
  'AE-DU': { name: "Dubayy", type: "Emirate" },
  'AE-FU': { name: "Al Fujayrah", type: "Emirate" },
  'AE-RK': { name: "Ra's al Khaymah", type: "Emirate" },
  'AE-SH': { name: "Ash Shāriqah", type: "Emirate" },
  'AE-UQ': { name: "Umm al Qaywayn", type: "Emirate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
