// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AF';
export const countryName = "Afghanistan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AF-BAL': { name: "Balkh", type: "Province" },
  'AF-BAM': { name: "Bāmyān", type: "Province" },
  'AF-BDG': { name: "Bādghīs", type: "Province" },
  'AF-BDS': { name: "Badakhshān", type: "Province" },
  'AF-BGL': { name: "Baghlān", type: "Province" },
  'AF-DAY': { name: "Dāykundī", type: "Province" },
  'AF-FRA': { name: "Farāh", type: "Province" },
  'AF-FYB': { name: "Fāryāb", type: "Province" },
  'AF-GHA': { name: "Ghaznī", type: "Province" },
  'AF-GHO': { name: "Ghōr", type: "Province" },
  'AF-HEL': { name: "Helmand", type: "Province" },
  'AF-HER': { name: "Herāt", type: "Province" },
  'AF-JOW': { name: "Jowzjān", type: "Province" },
  'AF-KAB': { name: "Kābul", type: "Province" },
  'AF-KAN': { name: "Kandahār", type: "Province" },
  'AF-KAP': { name: "Kāpīsā", type: "Province" },
  'AF-KDZ': { name: "Kunduz", type: "Province" },
  'AF-KHO': { name: "Khōst", type: "Province" },
  'AF-KNR': { name: "Kunar", type: "Province" },
  'AF-LAG': { name: "Laghmān", type: "Province" },
  'AF-LOG': { name: "Lōgar", type: "Province" },
  'AF-NAN': { name: "Nangarhār", type: "Province" },
  'AF-NIM': { name: "Nīmrōz", type: "Province" },
  'AF-NUR': { name: "Nūristān", type: "Province" },
  'AF-PAN': { name: "Panjshayr", type: "Province" },
  'AF-PAR': { name: "Parwān", type: "Province" },
  'AF-PIA': { name: "Paktiyā", type: "Province" },
  'AF-PKA': { name: "Paktīkā", type: "Province" },
  'AF-SAM': { name: "Samangān", type: "Province" },
  'AF-SAR': { name: "Sar-e Pul", type: "Province" },
  'AF-TAK': { name: "Takhār", type: "Province" },
  'AF-URU': { name: "Uruzgān", type: "Province" },
  'AF-WAR': { name: "Wardak", type: "Province" },
  'AF-ZAB': { name: "Zābul", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
