// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AG';
export const countryName = "Antigua and Barbuda";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AG-03': { name: "Saint George", type: "Parish" },
  'AG-04': { name: "Saint John", type: "Parish" },
  'AG-05': { name: "Saint Mary", type: "Parish" },
  'AG-06': { name: "Saint Paul", type: "Parish" },
  'AG-07': { name: "Saint Peter", type: "Parish" },
  'AG-08': { name: "Saint Philip", type: "Parish" },
  'AG-10': { name: "Barbuda", type: "Dependency" },
  'AG-11': { name: "Redonda", type: "Dependency" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
