// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AI';
export const countryName = "Anguilla";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AI-AI': { name: "Anguilla", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
