// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AL';
export const countryName = "Albania";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AL-01': { name: "Berat", type: "County" },
  'AL-02': { name: "Durrës", type: "County" },
  'AL-03': { name: "Elbasan", type: "County" },
  'AL-04': { name: "Fier", type: "County" },
  'AL-05': { name: "Gjirokastër", type: "County" },
  'AL-06': { name: "Korçë", type: "County" },
  'AL-07': { name: "Kukës", type: "County" },
  'AL-08': { name: "Lezhë", type: "County" },
  'AL-09': { name: "Dibër", type: "County" },
  'AL-10': { name: "Shkodër", type: "County" },
  'AL-11': { name: "Tiranë", type: "County" },
  'AL-12': { name: "Vlorë", type: "County" },
  'AL-BR': { name: "Berat", type: "District" },
  'AL-BU': { name: "Bulqizë", type: "District" },
  'AL-DI': { name: "Dibër", type: "District" },
  'AL-DL': { name: "Delvinë", type: "District" },
  'AL-DR': { name: "Durrës", type: "District" },
  'AL-DV': { name: "Devoll", type: "District" },
  'AL-EL': { name: "Elbasan", type: "District" },
  'AL-ER': { name: "Kolonjë", type: "District" },
  'AL-FR': { name: "Fier", type: "District" },
  'AL-GJ': { name: "Gjirokastër", type: "District" },
  'AL-GR': { name: "Gramsh", type: "District" },
  'AL-HA': { name: "Has", type: "District" },
  'AL-KA': { name: "Kavajë", type: "District" },
  'AL-KB': { name: "Kurbin", type: "District" },
  'AL-KC': { name: "Kuçovë", type: "District" },
  'AL-KO': { name: "Korçë", type: "District" },
  'AL-KR': { name: "Krujë", type: "District" },
  'AL-KU': { name: "Kukës", type: "District" },
  'AL-LB': { name: "Librazhd", type: "District" },
  'AL-LE': { name: "Lezhë", type: "District" },
  'AL-LU': { name: "Lushnjë", type: "District" },
  'AL-MK': { name: "Mallakastër", type: "District" },
  'AL-MM': { name: "Malësi e Madhe", type: "District" },
  'AL-MR': { name: "Mirditë", type: "District" },
  'AL-MT': { name: "Mat", type: "District" },
  'AL-PG': { name: "Pogradec", type: "District" },
  'AL-PQ': { name: "Peqin", type: "District" },
  'AL-PR': { name: "Përmet", type: "District" },
  'AL-PU': { name: "Pukë", type: "District" },
  'AL-SH': { name: "Shkodër", type: "District" },
  'AL-SK': { name: "Skrapar", type: "District" },
  'AL-SR': { name: "Sarandë", type: "District" },
  'AL-TE': { name: "Tepelenë", type: "District" },
  'AL-TP': { name: "Tropojë", type: "District" },
  'AL-TR': { name: "Tiranë", type: "District" },
  'AL-VL': { name: "Vlorë", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
