// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AM';
export const countryName = "Armenia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AM-AG': { name: "Aragac̣otn", type: "Region" },
  'AM-AR': { name: "Ararat", type: "Region" },
  'AM-AV': { name: "Armavir", type: "Region" },
  'AM-ER': { name: "Erevan", type: "City" },
  'AM-GR': { name: "Geġark'unik'", type: "Region" },
  'AM-KT': { name: "Kotayk'", type: "Region" },
  'AM-LO': { name: "Loṙi", type: "Region" },
  'AM-SH': { name: "Širak", type: "Region" },
  'AM-SU': { name: "Syunik'", type: "Region" },
  'AM-TV': { name: "Tavuš", type: "Region" },
  'AM-VD': { name: "Vayoć Jor", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
