// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AO';
export const countryName = "Angola";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AO-BGO': { name: "Bengo", type: "Province" },
  'AO-BGU': { name: "Benguela", type: "Province" },
  'AO-BIE': { name: "Bié", type: "Province" },
  'AO-CAB': { name: "Cabinda", type: "Province" },
  'AO-CCU': { name: "Kuando Kubango", type: "Province" },
  'AO-CNN': { name: "Cunene", type: "Province" },
  'AO-CNO': { name: "Kwanza Norte", type: "Province" },
  'AO-CUS': { name: "Kwanza Sul", type: "Province" },
  'AO-HUA': { name: "Huambo", type: "Province" },
  'AO-HUI': { name: "Huíla", type: "Province" },
  'AO-LNO': { name: "Lunda Norte", type: "Province" },
  'AO-LSU': { name: "Lunda Sul", type: "Province" },
  'AO-LUA': { name: "Luanda", type: "Province" },
  'AO-MAL': { name: "Malange", type: "Province" },
  'AO-MOX': { name: "Moxico", type: "Province" },
  'AO-NAM': { name: "Namibe", type: "Province" },
  'AO-UIG': { name: "Uíge", type: "Province" },
  'AO-ZAI': { name: "Zaire", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
