// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AQ';
export const countryName = "Antarctica";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AQ-AQ': { name: "Antarctica", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
