// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AR';
export const countryName = "Argentina";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AR-A': { name: "Salta", type: "Province" },
  'AR-B': { name: "Buenos Aires", type: "Province" },
  'AR-C': { name: "Ciudad Autónoma de Buenos Aires", type: "City" },
  'AR-D': { name: "San Luis", type: "Province" },
  'AR-E': { name: "Entre Ríos", type: "Province" },
  'AR-F': { name: "La Rioja", type: "Province" },
  'AR-G': { name: "Santiago del Estero", type: "Province" },
  'AR-H': { name: "Chaco", type: "Province" },
  'AR-J': { name: "San Juan", type: "Province" },
  'AR-K': { name: "Catamarca", type: "Province" },
  'AR-L': { name: "La Pampa", type: "Province" },
  'AR-M': { name: "Mendoza", type: "Province" },
  'AR-N': { name: "Misiones", type: "Province" },
  'AR-P': { name: "Formosa", type: "Province" },
  'AR-Q': { name: "Neuquén", type: "Province" },
  'AR-R': { name: "Río Negro", type: "Province" },
  'AR-S': { name: "Santa Fe", type: "Province" },
  'AR-T': { name: "Tucumán", type: "Province" },
  'AR-U': { name: "Chubut", type: "Province" },
  'AR-V': { name: "Tierra del Fuego", type: "Province" },
  'AR-W': { name: "Corrientes", type: "Province" },
  'AR-X': { name: "Córdoba", type: "Province" },
  'AR-Y': { name: "Jujuy", type: "Province" },
  'AR-Z': { name: "Santa Cruz", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
