// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AS';
export const countryName = "American Samoa";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AS-AS': { name: "American Samoa", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
