// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AT';
export const countryName = "Austria";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AT-1': { name: "Burgenland", type: "Federal länder" },
  'AT-2': { name: "Kärnten", type: "Federal länder" },
  'AT-3': { name: "Niederösterreich", type: "Federal länder" },
  'AT-4': { name: "Oberösterreich", type: "Federal länder" },
  'AT-5': { name: "Salzburg", type: "Federal länder" },
  'AT-6': { name: "Steiermark", type: "Federal länder" },
  'AT-7': { name: "Tirol", type: "Federal länder" },
  'AT-8': { name: "Vorarlberg", type: "Federal länder" },
  'AT-9': { name: "Wien", type: "Federal länder" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
