// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AU';
export const countryName = "Australia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AU-ACT': { name: "Australian Capital Territory", type: "Territory" },
  'AU-NSW': { name: "New South Wales", type: "State" },
  'AU-NT': { name: "Northern Territory", type: "Territory" },
  'AU-QLD': { name: "Queensland", type: "State" },
  'AU-SA': { name: "South Australia", type: "State" },
  'AU-TAS': { name: "Tasmania", type: "State" },
  'AU-VIC': { name: "Victoria", type: "State" },
  'AU-WA': { name: "Western Australia", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
