// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AW';
export const countryName = "Aruba";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AW-AW': { name: "Aruba", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
