// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'AX';
export const countryName = "Åland Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'AX-AX': { name: "Åland Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
