// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BA';
export const countryName = "Bosnia and Herzegovina";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BA-01': { name: "Unsko-sanska županija", type: "Canton" },
  'BA-02': { name: "Posavska županija", type: "Canton" },
  'BA-03': { name: "Tuzlanska županija", type: "Canton" },
  'BA-04': { name: "Zeničko-dobojska županija", type: "Canton" },
  'BA-05': { name: "Bosansko-podrinjska županija", type: "Canton" },
  'BA-06': { name: "Srednjobosanska županija", type: "Canton" },
  'BA-07': { name: "Hercegovačko-neretvanska županija", type: "Canton" },
  'BA-08': { name: "Zapadnohercegovačka županija", type: "Canton" },
  'BA-09': { name: "Kanton Sarajevo", type: "Canton" },
  'BA-10': { name: "Kanton br. 10", type: "Canton" },
  'BA-BIH': { name: "Federacija Bosne i Hercegovine", type: "Entity" },
  'BA-BRC': { name: "Brčko distrikt", type: "District with special status" },
  'BA-SRP': { name: "Republika Srpska", type: "Entity" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
