// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BB';
export const countryName = "Barbados";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BB-01': { name: "Christ Church", type: "Parish" },
  'BB-02': { name: "Saint Andrew", type: "Parish" },
  'BB-03': { name: "Saint George", type: "Parish" },
  'BB-04': { name: "Saint James", type: "Parish" },
  'BB-05': { name: "Saint John", type: "Parish" },
  'BB-06': { name: "Saint Joseph", type: "Parish" },
  'BB-07': { name: "Saint Lucy", type: "Parish" },
  'BB-08': { name: "Saint Michael", type: "Parish" },
  'BB-09': { name: "Saint Peter", type: "Parish" },
  'BB-10': { name: "Saint Philip", type: "Parish" },
  'BB-11': { name: "Saint Thomas", type: "Parish" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
