// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BE';
export const countryName = "Belgium";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BE-BRU': { name: "Brussels Hoofdstedelijk Gewest", type: "Region" },
  'BE-VAN': { name: "Antwerpen", type: "Province" },
  'BE-VBR': { name: "Vlaams-Brabant", type: "Province" },
  'BE-VLG': { name: "Vlaams Gewest", type: "Region" },
  'BE-VLI': { name: "Limburg", type: "Province" },
  'BE-VOV': { name: "Oost-Vlaanderen", type: "Province" },
  'BE-VWV': { name: "West-Vlaanderen", type: "Province" },
  'BE-WAL': { name: "wallonne, Région", type: "Region" },
  'BE-WBR': { name: "Brabant wallon", type: "Province" },
  'BE-WHT': { name: "Hainaut", type: "Province" },
  'BE-WLG': { name: "Liège", type: "Province" },
  'BE-WLX': { name: "Luxembourg", type: "Province" },
  'BE-WNA': { name: "Namur", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
