// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BG';
export const countryName = "Bulgaria";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BG-01': { name: "Blagoevgrad", type: "Region" },
  'BG-02': { name: "Burgas", type: "Region" },
  'BG-03': { name: "Varna", type: "Region" },
  'BG-04': { name: "Veliko Tarnovo", type: "Region" },
  'BG-05': { name: "Vidin", type: "Region" },
  'BG-06': { name: "Vratsa", type: "Region" },
  'BG-07': { name: "Gabrovo", type: "Region" },
  'BG-08': { name: "Dobrich", type: "Region" },
  'BG-09': { name: "Kardzhali", type: "Region" },
  'BG-10': { name: "Kyustendil", type: "Region" },
  'BG-11': { name: "Lovech", type: "Region" },
  'BG-12': { name: "Montana", type: "Region" },
  'BG-13': { name: "Pazardzhik", type: "Region" },
  'BG-14': { name: "Pernik", type: "Region" },
  'BG-15': { name: "Pleven", type: "Region" },
  'BG-16': { name: "Plovdiv", type: "Region" },
  'BG-17': { name: "Razgrad", type: "Region" },
  'BG-18': { name: "Ruse", type: "Region" },
  'BG-19': { name: "Silistra", type: "Region" },
  'BG-20': { name: "Sliven", type: "Region" },
  'BG-21': { name: "Smolyan", type: "Region" },
  'BG-22': { name: "Sofia", type: "Region" },
  'BG-23': { name: "Sofia", type: "Region" },
  'BG-24': { name: "Stara Zagora", type: "Region" },
  'BG-25': { name: "Targovishte", type: "Region" },
  'BG-26': { name: "Haskovo", type: "Region" },
  'BG-27': { name: "Shumen", type: "Region" },
  'BG-28': { name: "Yambol", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
