// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BH';
export const countryName = "Bahrain";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BH-13': { name: "Al Manāmah", type: "Governorate" },
  'BH-14': { name: "Al Janūbīyah", type: "Governorate" },
  'BH-15': { name: "Al Muḩarraq", type: "Governorate" },
  'BH-16': { name: "Al Wusţá", type: "Governorate" },
  'BH-17': { name: "Ash Shamālīyah", type: "Governorate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
