// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BI';
export const countryName = "Burundi";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BI-BB': { name: "Bubanza", type: "Province" },
  'BI-BL': { name: "Bujumbura Rural", type: "Province" },
  'BI-BM': { name: "Bujumbura Mairie", type: "Province" },
  'BI-BR': { name: "Bururi", type: "Province" },
  'BI-CA': { name: "Cankuzo", type: "Province" },
  'BI-CI': { name: "Cibitoke", type: "Province" },
  'BI-GI': { name: "Gitega", type: "Province" },
  'BI-KI': { name: "Kirundo", type: "Province" },
  'BI-KR': { name: "Karuzi", type: "Province" },
  'BI-KY': { name: "Kayanza", type: "Province" },
  'BI-MA': { name: "Makamba", type: "Province" },
  'BI-MU': { name: "Muramvya", type: "Province" },
  'BI-MW': { name: "Mwaro", type: "Province" },
  'BI-MY': { name: "Muyinga", type: "Province" },
  'BI-NG': { name: "Ngozi", type: "Province" },
  'BI-RT': { name: "Rutana", type: "Province" },
  'BI-RY': { name: "Ruyigi", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
