// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BJ';
export const countryName = "Benin";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BJ-AK': { name: "Atakora", type: "Department" },
  'BJ-AL': { name: "Alibori", type: "Department" },
  'BJ-AQ': { name: "Atlantique", type: "Department" },
  'BJ-BO': { name: "Borgou", type: "Department" },
  'BJ-CO': { name: "Collines", type: "Department" },
  'BJ-DO': { name: "Donga", type: "Department" },
  'BJ-KO': { name: "Kouffo", type: "Department" },
  'BJ-LI': { name: "Littoral", type: "Department" },
  'BJ-MO': { name: "Mono", type: "Department" },
  'BJ-OU': { name: "Ouémé", type: "Department" },
  'BJ-PL': { name: "Plateau", type: "Department" },
  'BJ-ZO': { name: "Zou", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
