// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BL';
export const countryName = "St. Barthélemy";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BL-BL': { name: "St. Barthélemy", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
