// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BM';
export const countryName = "Bermuda";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BM-BM': { name: "Bermuda", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
