// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BN';
export const countryName = "Brunei Darussalam";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BN-BE': { name: "Belait", type: "District" },
  'BN-BM': { name: "Brunei-Muara", type: "District" },
  'BN-TE': { name: "Temburong", type: "District" },
  'BN-TU': { name: "Tutong", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
