// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BO';
export const countryName = "Bolivia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BO-B': { name: "El Beni", type: "Department" },
  'BO-C': { name: "Cochabamba", type: "Department" },
  'BO-H': { name: "Chuquisaca", type: "Department" },
  'BO-L': { name: "La Paz", type: "Department" },
  'BO-N': { name: "Pando", type: "Department" },
  'BO-O': { name: "Oruro", type: "Department" },
  'BO-P': { name: "Potosí", type: "Department" },
  'BO-S': { name: "Santa Cruz", type: "Department" },
  'BO-T': { name: "Tarija", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
