// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BQ';
export const countryName = "Bonaire, Sint Eustatius and Saba";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BQ-BO': { name: "Bonaire", type: "Special municipality" },
  'BQ-SA': { name: "Saba", type: "Special municipality" },
  'BQ-SE': { name: "Sint Eustatius", type: "Special municipality" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
