// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BR';
export const countryName = "Brazil";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BR-AC': { name: "Acre", type: "State" },
  'BR-AL': { name: "Alagoas", type: "State" },
  'BR-AM': { name: "Amazonas", type: "State" },
  'BR-AP': { name: "Amapá", type: "State" },
  'BR-BA': { name: "Bahia", type: "State" },
  'BR-CE': { name: "Ceará", type: "State" },
  'BR-DF': { name: "Distrito Federal", type: "Federal district" },
  'BR-ES': { name: "Espírito Santo", type: "State" },
  'BR-GO': { name: "Goiás", type: "State" },
  'BR-MA': { name: "Maranhão", type: "State" },
  'BR-MG': { name: "Minas Gerais", type: "State" },
  'BR-MS': { name: "Mato Grosso do Sul", type: "State" },
  'BR-MT': { name: "Mato Grosso", type: "State" },
  'BR-PA': { name: "Pará", type: "State" },
  'BR-PB': { name: "Paraíba", type: "State" },
  'BR-PE': { name: "Pernambuco", type: "State" },
  'BR-PI': { name: "Piauí", type: "State" },
  'BR-PR': { name: "Paraná", type: "State" },
  'BR-RJ': { name: "Rio de Janeiro", type: "State" },
  'BR-RN': { name: "Rio Grande do Norte", type: "State" },
  'BR-RO': { name: "Rondônia", type: "State" },
  'BR-RR': { name: "Roraima", type: "State" },
  'BR-RS': { name: "Rio Grande do Sul", type: "State" },
  'BR-SC': { name: "Santa Catarina", type: "State" },
  'BR-SE': { name: "Sergipe", type: "State" },
  'BR-SP': { name: "São Paulo", type: "State" },
  'BR-TO': { name: "Tocantins", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
