// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BS';
export const countryName = "Bahamas";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BS-AK': { name: "Acklins", type: "District" },
  'BS-BI': { name: "Bimini", type: "District" },
  'BS-BP': { name: "Black Point", type: "District" },
  'BS-BY': { name: "Berry Islands", type: "District" },
  'BS-CE': { name: "Central Eleuthera", type: "District" },
  'BS-CI': { name: "Cat Island", type: "District" },
  'BS-CK': { name: "Crooked Island and Long Cay", type: "District" },
  'BS-CO': { name: "Central Abaco", type: "District" },
  'BS-CS': { name: "Central Andros", type: "District" },
  'BS-EG': { name: "East Grand Bahama", type: "District" },
  'BS-EX': { name: "Exuma", type: "District" },
  'BS-FP': { name: "City of Freeport", type: "District" },
  'BS-GC': { name: "Grand Cay", type: "District" },
  'BS-HI': { name: "Harbour Island", type: "District" },
  'BS-HT': { name: "Hope Town", type: "District" },
  'BS-IN': { name: "Inagua", type: "District" },
  'BS-LI': { name: "Long Island", type: "District" },
  'BS-MC': { name: "Mangrove Cay", type: "District" },
  'BS-MG': { name: "Mayaguana", type: "District" },
  'BS-MI': { name: "Moore's Island", type: "District" },
  'BS-NE': { name: "North Eleuthera", type: "District" },
  'BS-NO': { name: "North Abaco", type: "District" },
  'BS-NS': { name: "North Andros", type: "District" },
  'BS-RC': { name: "Rum Cay", type: "District" },
  'BS-RI': { name: "Ragged Island", type: "District" },
  'BS-SA': { name: "South Andros", type: "District" },
  'BS-SE': { name: "South Eleuthera", type: "District" },
  'BS-SO': { name: "South Abaco", type: "District" },
  'BS-SS': { name: "San Salvador", type: "District" },
  'BS-SW': { name: "Spanish Wells", type: "District" },
  'BS-WG': { name: "West Grand Bahama", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
