// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BT';
export const countryName = "Bhutan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BT-11': { name: "Paro", type: "District" },
  'BT-12': { name: "Chhukha", type: "District" },
  'BT-13': { name: "Ha", type: "District" },
  'BT-14': { name: "Samtse", type: "District" },
  'BT-15': { name: "Thimphu", type: "District" },
  'BT-21': { name: "Tsirang", type: "District" },
  'BT-22': { name: "Dagana", type: "District" },
  'BT-23': { name: "Punakha", type: "District" },
  'BT-24': { name: "Wangdue Phodrang", type: "District" },
  'BT-31': { name: "Sarpang", type: "District" },
  'BT-32': { name: "Trongsa", type: "District" },
  'BT-33': { name: "Bumthang", type: "District" },
  'BT-34': { name: "Zhemgang", type: "District" },
  'BT-41': { name: "Trashigang", type: "District" },
  'BT-42': { name: "Monggar", type: "District" },
  'BT-43': { name: "Pemagatshel", type: "District" },
  'BT-44': { name: "Lhuentse", type: "District" },
  'BT-45': { name: "Samdrup Jongkha", type: "District" },
  'BT-GA': { name: "Gasa", type: "District" },
  'BT-TY': { name: "Trashi Yangtse", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
