// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BV';
export const countryName = "Bouvet Island";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BV-BV': { name: "Bouvet Island", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
