// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BW';
export const countryName = "Botswana";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BW-CE': { name: "Central", type: "District" },
  'BW-CH': { name: "Chobe", type: "District" },
  'BW-FR': { name: "Francistown", type: "City" },
  'BW-GA': { name: "Gaborone", type: "City" },
  'BW-GH': { name: "Ghanzi", type: "District" },
  'BW-JW': { name: "Jwaneng", type: "Town" },
  'BW-KG': { name: "Kgalagadi", type: "District" },
  'BW-KL': { name: "Kgatleng", type: "District" },
  'BW-KW': { name: "Kweneng", type: "District" },
  'BW-LO': { name: "Lobatse", type: "Town" },
  'BW-NE': { name: "North East", type: "District" },
  'BW-NW': { name: "North West", type: "District" },
  'BW-SE': { name: "South East", type: "District" },
  'BW-SO': { name: "Southern", type: "District" },
  'BW-SP': { name: "Selibe Phikwe", type: "Town" },
  'BW-ST': { name: "Sowa Town", type: "Town" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
