// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BY';
export const countryName = "Belarus";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BY-BR': { name: "Bresckaja voblasć", type: "Oblast" },
  'BY-HM': { name: "Gorod Minsk", type: "City" },
  'BY-HO': { name: "Gomel'skaja oblast'", type: "Oblast" },
  'BY-HR': { name: "Grodnenskaja oblast'", type: "Oblast" },
  'BY-MA': { name: "Mahilioŭskaja voblasć", type: "Oblast" },
  'BY-MI': { name: "Minskaja oblast'", type: "Oblast" },
  'BY-VI': { name: "Viciebskaja voblasć", type: "Oblast" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
