// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'BZ';
export const countryName = "Belize";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'BZ-BZ': { name: "Belize", type: "District" },
  'BZ-CY': { name: "Cayo", type: "District" },
  'BZ-CZL': { name: "Corozal", type: "District" },
  'BZ-OW': { name: "Orange Walk", type: "District" },
  'BZ-SC': { name: "Stann Creek", type: "District" },
  'BZ-TOL': { name: "Toledo", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
