// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CA';
export const countryName = "Canada";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CA-AB': { name: "Alberta", type: "Province" },
  'CA-BC': { name: "British Columbia", type: "Province" },
  'CA-MB': { name: "Manitoba", type: "Province" },
  'CA-NB': { name: "New Brunswick", type: "Province" },
  'CA-NL': { name: "Newfoundland and Labrador", type: "Province" },
  'CA-NS': { name: "Nova Scotia", type: "Province" },
  'CA-NT': { name: "Northwest Territories", type: "Territory" },
  'CA-NU': { name: "Nunavut", type: "Territory" },
  'CA-ON': { name: "Ontario", type: "Province" },
  'CA-PE': { name: "Prince Edward Island", type: "Province" },
  'CA-QC': { name: "Quebec", type: "Province" },
  'CA-SK': { name: "Saskatchewan", type: "Province" },
  'CA-YT': { name: "Yukon", type: "Territory" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
