// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CC';
export const countryName = "Cocos  Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CC-CC': { name: "Cocos  Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
