// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CD';
export const countryName = "Congo, The Democratic Republic Of The";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CD-BC': { name: "Bas-Congo", type: "Province" },
  'CD-BN': { name: "Bandundu", type: "Province" },
  'CD-EQ': { name: "Équateur", type: "Province" },
  'CD-KA': { name: "Katanga", type: "Province" },
  'CD-KE': { name: "Kasai-Oriental", type: "Province" },
  'CD-KN': { name: "Kinshasa", type: "City" },
  'CD-KW': { name: "Kasai-Occidental", type: "Province" },
  'CD-MA': { name: "Maniema", type: "Province" },
  'CD-NK': { name: "Nord-Kivu", type: "Province" },
  'CD-OR': { name: "Orientale", type: "Province" },
  'CD-SK': { name: "Sud-Kivu", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
