// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CF';
export const countryName = "Central African Republic";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CF-AC': { name: "Ouham", type: "Prefecture" },
  'CF-BB': { name: "Bamïngï-Bangoran", type: "Prefecture" },
  'CF-BGF': { name: "Bangî", type: "Commune" },
  'CF-BK': { name: "Basse-Kotto", type: "Prefecture" },
  'CF-HK': { name: "Haute-Kotto", type: "Prefecture" },
  'CF-HM': { name: "Haut-Mbomou", type: "Prefecture" },
  'CF-HS': { name: "Haute-Sangha / Mambéré-Kadéï", type: "Prefecture" },
  'CF-KB': { name: "Gïrïbïngï", type: "Economic prefecture" },
  'CF-KG': { name: "Kemö-Gïrïbïngï", type: "Prefecture" },
  'CF-LB': { name: "Lobaye", type: "Prefecture" },
  'CF-MB': { name: "Mbomou", type: "Prefecture" },
  'CF-MP': { name: "Ömbëlä-Pökö", type: "Prefecture" },
  'CF-NM': { name: "Nana-Mambéré", type: "Prefecture" },
  'CF-OP': { name: "Ouham-Pendé", type: "Prefecture" },
  'CF-SE': { name: "Sangä", type: "Economic prefecture" },
  'CF-UK': { name: "Ouaka", type: "Prefecture" },
  'CF-VK': { name: "Vakaga", type: "Prefecture" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
