// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CG';
export const countryName = "Congo";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CG-11': { name: "Bouenza", type: "Department" },
  'CG-12': { name: "Pool", type: "Department" },
  'CG-13': { name: "Sangha", type: "Department" },
  'CG-14': { name: "Plateaux", type: "Department" },
  'CG-15': { name: "Cuvette-Ouest", type: "Department" },
  'CG-16': { name: "Pointe-Noire", type: "Department" },
  'CG-2': { name: "Lékoumou", type: "Department" },
  'CG-5': { name: "Kouilou", type: "Department" },
  'CG-7': { name: "Likouala", type: "Department" },
  'CG-8': { name: "Cuvette", type: "Department" },
  'CG-9': { name: "Niari", type: "Department" },
  'CG-BZV': { name: "Brazzaville", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
