// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CH';
export const countryName = "Switzerland";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CH-AG': { name: "Aargau", type: "Canton" },
  'CH-AI': { name: "Appenzell Innerrhoden", type: "Canton" },
  'CH-AR': { name: "Appenzell Ausserrhoden", type: "Canton" },
  'CH-BE': { name: "Bern", type: "Canton" },
  'CH-BL': { name: "Basel-Landschaft", type: "Canton" },
  'CH-BS': { name: "Basel-Stadt", type: "Canton" },
  'CH-FR': { name: "Freiburg", type: "Canton" },
  'CH-GE': { name: "Genève", type: "Canton" },
  'CH-GL': { name: "Glarus", type: "Canton" },
  'CH-GR': { name: "Graubünden", type: "Canton" },
  'CH-JU': { name: "Jura", type: "Canton" },
  'CH-LU': { name: "Luzern", type: "Canton" },
  'CH-NE': { name: "Neuchâtel", type: "Canton" },
  'CH-NW': { name: "Nidwalden", type: "Canton" },
  'CH-OW': { name: "Obwalden", type: "Canton" },
  'CH-SG': { name: "Sankt Gallen", type: "Canton" },
  'CH-SH': { name: "Schaffhausen", type: "Canton" },
  'CH-SO': { name: "Solothurn", type: "Canton" },
  'CH-SZ': { name: "Schwyz", type: "Canton" },
  'CH-TG': { name: "Thurgau", type: "Canton" },
  'CH-TI': { name: "Ticino", type: "Canton" },
  'CH-UR': { name: "Uri", type: "Canton" },
  'CH-VD': { name: "Vaud", type: "Canton" },
  'CH-VS': { name: "Valais", type: "Canton" },
  'CH-ZG': { name: "Zug", type: "Canton" },
  'CH-ZH': { name: "Zürich", type: "Canton" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
