// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CI';
export const countryName = "Côte D'Ivoire";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CI-01': { name: "Lagunes", type: "Region" },
  'CI-02': { name: "Haut-Sassandra", type: "Region" },
  'CI-03': { name: "Savanes", type: "Region" },
  'CI-04': { name: "Vallée du Bandama", type: "Region" },
  'CI-05': { name: "Moyen-Comoé", type: "Region" },
  'CI-06': { name: "18 Montagnes", type: "Region" },
  'CI-07': { name: "Lacs", type: "Region" },
  'CI-08': { name: "Zanzan", type: "Region" },
  'CI-09': { name: "Bas-Sassandra", type: "Region" },
  'CI-10': { name: "Denguélé", type: "Region" },
  'CI-11': { name: "Nzi-Comoé", type: "Region" },
  'CI-12': { name: "Marahoué", type: "Region" },
  'CI-13': { name: "Sud-Comoé", type: "Region" },
  'CI-14': { name: "Worodougou", type: "Region" },
  'CI-15': { name: "Sud-Bandama", type: "Region" },
  'CI-16': { name: "Agnébi", type: "Region" },
  'CI-17': { name: "Bafing", type: "Region" },
  'CI-18': { name: "Fromager", type: "Region" },
  'CI-19': { name: "Moyen-Cavally", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
