// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CK';
export const countryName = "Cook Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CK-CK': { name: "Cook Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
