// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CL';
export const countryName = "Chile";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CL-AI': { name: "Aysén", type: "Region" },
  'CL-AN': { name: "Antofagasta", type: "Region" },
  'CL-AP': { name: "Arica y Parinacota", type: "Region" },
  'CL-AR': { name: "Araucanía", type: "Region" },
  'CL-AT': { name: "Atacama", type: "Region" },
  'CL-BI': { name: "Biobío", type: "Region" },
  'CL-CO': { name: "Coquimbo", type: "Region" },
  'CL-LI': { name: "Libertador General Bernardo O'Higgins", type: "Region" },
  'CL-LL': { name: "Los Lagos", type: "Region" },
  'CL-LR': { name: "Los Ríos", type: "Region" },
  'CL-MA': { name: "Magallanes", type: "Region" },
  'CL-ML': { name: "Maule", type: "Region" },
  'CL-RM': { name: "Región Metropolitana de Santiago", type: "Region" },
  'CL-TA': { name: "Tarapacá", type: "Region" },
  'CL-VS': { name: "Valparaíso", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
