// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CM';
export const countryName = "Cameroon";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CM-AD': { name: "Adamaoua", type: "Region" },
  'CM-CE': { name: "Centre", type: "Region" },
  'CM-EN': { name: "Extrême-Nord", type: "Region" },
  'CM-ES': { name: "East", type: "Region" },
  'CM-LT': { name: "Littoral", type: "Region" },
  'CM-NO': { name: "Nord", type: "Region" },
  'CM-NW': { name: "Nord-Ouest", type: "Region" },
  'CM-OU': { name: "Ouest", type: "Region" },
  'CM-SU': { name: "South", type: "Region" },
  'CM-SW': { name: "South-West", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
