// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CN';
export const countryName = "China";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CN-11': { name: "Beijing", type: "Municipality" },
  'CN-12': { name: "Tianjin", type: "Municipality" },
  'CN-13': { name: "Hebei", type: "Province" },
  'CN-14': { name: "Shanxi", type: "Province" },
  'CN-15': { name: "Nei Mongol", type: "Autonomous region" },
  'CN-21': { name: "Liaoning", type: "Province" },
  'CN-22': { name: "Jilin", type: "Province" },
  'CN-23': { name: "Heilongjiang", type: "Province" },
  'CN-31': { name: "Shanghai", type: "Municipality" },
  'CN-32': { name: "Jiangsu", type: "Province" },
  'CN-33': { name: "Zhejiang", type: "Province" },
  'CN-34': { name: "Anhui", type: "Province" },
  'CN-35': { name: "Fujian", type: "Province" },
  'CN-36': { name: "Jiangxi", type: "Province" },
  'CN-37': { name: "Shandong", type: "Province" },
  'CN-41': { name: "Henan", type: "Province" },
  'CN-42': { name: "Hubei", type: "Province" },
  'CN-43': { name: "Hunan", type: "Province" },
  'CN-44': { name: "Guangdong", type: "Province" },
  'CN-45': { name: "Guangxi", type: "Autonomous region" },
  'CN-46': { name: "Hainan", type: "Province" },
  'CN-50': { name: "Chongqing", type: "Municipality" },
  'CN-51': { name: "Sichuan", type: "Province" },
  'CN-52': { name: "Guizhou", type: "Province" },
  'CN-53': { name: "Yunnan", type: "Province" },
  'CN-54': { name: "Xizang", type: "Autonomous region" },
  'CN-61': { name: "Shaanxi", type: "Province" },
  'CN-62': { name: "Gansu", type: "Province" },
  'CN-63': { name: "Qinghai", type: "Province" },
  'CN-64': { name: "Ningxia", type: "Autonomous region" },
  'CN-65': { name: "Xinjiang", type: "Autonomous region" },
  'CN-71': { name: "Taiwan", type: "Province" },
  'CN-91': { name: "Hong Kong", type: "Special administrative region" },
  'CN-92': { name: "Aomen", type: "Special administrative region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
