// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CN';
export const countryName = "China";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CN-AH': { name: "Anhui", type: "Province" },
  'CN-BJ': { name: "Beijing", type: "Municipality" },
  'CN-CQ': { name: "Chongqing", type: "Municipality" },
  'CN-FJ': { name: "Fujian", type: "Province" },
  'CN-GD': { name: "Guangdong", type: "Province" },
  'CN-GS': { name: "Gansu", type: "Province" },
  'CN-GX': { name: "Guangxi", type: "Autonomous region" },
  'CN-GZ': { name: "Guizhou", type: "Province" },
  'CN-HA': { name: "Henan", type: "Province" },
  'CN-HB': { name: "Hubei", type: "Province" },
  'CN-HE': { name: "Hebei", type: "Province" },
  'CN-HI': { name: "Hainan", type: "Province" },
  'CN-HK': { name: "Hong Kong", type: "Special administrative region" },
  'CN-HL': { name: "Heilongjiang", type: "Province" },
  'CN-HN': { name: "Hunan", type: "Province" },
  'CN-JL': { name: "Jilin", type: "Province" },
  'CN-JS': { name: "Jiangsu", type: "Province" },
  'CN-JX': { name: "Jiangxi", type: "Province" },
  'CN-LN': { name: "Liaoning", type: "Province" },
  'CN-MO': { name: "Aomen", type: "Special administrative region" },
  'CN-NM': { name: "Nei Mongol", type: "Autonomous region" },
  'CN-NX': { name: "Ningxia", type: "Autonomous region" },
  'CN-QH': { name: "Qinghai", type: "Province" },
  'CN-SC': { name: "Sichuan", type: "Province" },
  'CN-SD': { name: "Shandong", type: "Province" },
  'CN-SH': { name: "Shanghai", type: "Municipality" },
  'CN-SN': { name: "Shaanxi", type: "Province" },
  'CN-SX': { name: "Shanxi", type: "Province" },
  'CN-TJ': { name: "Tianjin", type: "Municipality" },
  'CN-TW': { name: "Taiwan", type: "Province" },
  'CN-XJ': { name: "Xinjiang", type: "Autonomous region" },
  'CN-XZ': { name: "Xizang", type: "Autonomous region" },
  'CN-YN': { name: "Yunnan", type: "Province" },
  'CN-ZJ': { name: "Zhejiang", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
