// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CO';
export const countryName = "Colombia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CO-AMA': { name: "Amazonas", type: "Department" },
  'CO-ANT': { name: "Antioquia", type: "Department" },
  'CO-ARA': { name: "Arauca", type: "Department" },
  'CO-ATL': { name: "Atlántico", type: "Department" },
  'CO-BOL': { name: "Bolívar", type: "Department" },
  'CO-BOY': { name: "Boyacá", type: "Department" },
  'CO-CAL': { name: "Caldas", type: "Department" },
  'CO-CAQ': { name: "Caquetá", type: "Department" },
  'CO-CAS': { name: "Casanare", type: "Department" },
  'CO-CAU': { name: "Cauca", type: "Department" },
  'CO-CES': { name: "Cesar", type: "Department" },
  'CO-CHO': { name: "Chocó", type: "Department" },
  'CO-COR': { name: "Córdoba", type: "Department" },
  'CO-CUN': { name: "Cundinamarca", type: "Department" },
  'CO-DC': { name: "Distrito Capital de Bogotá", type: "Capital district" },
  'CO-GUA': { name: "Guainía", type: "Department" },
  'CO-GUV': { name: "Guaviare", type: "Department" },
  'CO-HUI': { name: "Huila", type: "Department" },
  'CO-LAG': { name: "La Guajira", type: "Department" },
  'CO-MAG': { name: "Magdalena", type: "Department" },
  'CO-MET': { name: "Meta", type: "Department" },
  'CO-NAR': { name: "Nariño", type: "Department" },
  'CO-NSA': { name: "Norte de Santander", type: "Department" },
  'CO-PUT': { name: "Putumayo", type: "Department" },
  'CO-QUI': { name: "Quindío", type: "Department" },
  'CO-RIS': { name: "Risaralda", type: "Department" },
  'CO-SAN': { name: "Santander", type: "Department" },
  'CO-SAP': { name: "San Andrés, Providencia y Santa Catalina", type: "Department" },
  'CO-SUC': { name: "Sucre", type: "Department" },
  'CO-TOL': { name: "Tolima", type: "Department" },
  'CO-VAC': { name: "Valle del Cauca", type: "Department" },
  'CO-VAU': { name: "Vaupés", type: "Department" },
  'CO-VID': { name: "Vichada", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
