// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CR';
export const countryName = "Costa Rica";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CR-A': { name: "Alajuela", type: "Province" },
  'CR-C': { name: "Cartago", type: "Province" },
  'CR-G': { name: "Guanacaste", type: "Province" },
  'CR-H': { name: "Heredia", type: "Province" },
  'CR-L': { name: "Limón", type: "Province" },
  'CR-P': { name: "Puntarenas", type: "Province" },
  'CR-SJ': { name: "San José", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
