// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CU';
export const countryName = "Cuba";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CU-01': { name: "Pinar del Río", type: "Province" },
  'CU-03': { name: "La Habana", type: "Province" },
  'CU-04': { name: "Matanzas", type: "Province" },
  'CU-05': { name: "Villa Clara", type: "Province" },
  'CU-06': { name: "Cienfuegos", type: "Province" },
  'CU-07': { name: "Sancti Spíritus", type: "Province" },
  'CU-08': { name: "Ciego de Ávila", type: "Province" },
  'CU-09': { name: "Camagüey", type: "Province" },
  'CU-10': { name: "Las Tunas", type: "Province" },
  'CU-11': { name: "Holguín", type: "Province" },
  'CU-12': { name: "Granma", type: "Province" },
  'CU-13': { name: "Santiago de Cuba", type: "Province" },
  'CU-14': { name: "Guantánamo", type: "Province" },
  'CU-15': { name: "Artemisa", type: "Province" },
  'CU-16': { name: "Mayabeque", type: "Province" },
  'CU-99': { name: "Isla de la Juventud", type: "Special municipality" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
