// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CV';
export const countryName = "Cape Verde";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CV-B': { name: "Ilhas de Barlavento", type: "Geographical region" },
  'CV-BR': { name: "Brava", type: "Municipality" },
  'CV-BV': { name: "Boa Vista", type: "Municipality" },
  'CV-CA': { name: "Santa Catarina", type: "Municipality" },
  'CV-CF': { name: "Santa Catarina do Fogo", type: "Municipality" },
  'CV-CR': { name: "Santa Cruz", type: "Municipality" },
  'CV-MA': { name: "Maio", type: "Municipality" },
  'CV-MO': { name: "Mosteiros", type: "Municipality" },
  'CV-PA': { name: "Paul", type: "Municipality" },
  'CV-PN': { name: "Porto Novo", type: "Municipality" },
  'CV-PR': { name: "Praia", type: "Municipality" },
  'CV-RB': { name: "Ribeira Brava", type: "Municipality" },
  'CV-RG': { name: "Ribeira Grande", type: "Municipality" },
  'CV-RS': { name: "Ribeira Grande de Santiago", type: "Municipality" },
  'CV-S': { name: "Ilhas de Sotavento", type: "Geographical region" },
  'CV-SD': { name: "São Domingos", type: "Municipality" },
  'CV-SF': { name: "São Filipe", type: "Municipality" },
  'CV-SL': { name: "Sal", type: "Municipality" },
  'CV-SM': { name: "São Miguel", type: "Municipality" },
  'CV-SO': { name: "São Lourenço dos Órgãos", type: "Municipality" },
  'CV-SS': { name: "São Salvador do Mundo", type: "Municipality" },
  'CV-SV': { name: "São Vicente", type: "Municipality" },
  'CV-TA': { name: "Tarrafal", type: "Municipality" },
  'CV-TS': { name: "Tarrafal de São Nicolau", type: "Municipality" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
