// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CW';
export const countryName = "Curaçao";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CW-CW': { name: "Curaçao", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
