// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CX';
export const countryName = "Christmas Island";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CX-CX': { name: "Christmas Island", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
