// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'CY';
export const countryName = "Cyprus";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'CY-01': { name: "Lefkoşa", type: "District" },
  'CY-02': { name: "Lemesos", type: "District" },
  'CY-03': { name: "Larnaka", type: "District" },
  'CY-04': { name: "Ammochostos", type: "District" },
  'CY-05': { name: "Baf", type: "District" },
  'CY-06': { name: "Girne", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
