// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'DE';
export const countryName = "Germany";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'DE-BB': { name: "Brandenburg", type: "Länder" },
  'DE-BE': { name: "Berlin", type: "Länder" },
  'DE-BW': { name: "Baden-Württemberg", type: "Länder" },
  'DE-BY': { name: "Bayern", type: "Länder" },
  'DE-HB': { name: "Bremen", type: "Länder" },
  'DE-HE': { name: "Hessen", type: "Länder" },
  'DE-HH': { name: "Hamburg", type: "Länder" },
  'DE-MV': { name: "Mecklenburg-Vorpommern", type: "Länder" },
  'DE-NI': { name: "Niedersachsen", type: "Länder" },
  'DE-NW': { name: "Nordrhein-Westfalen", type: "Länder" },
  'DE-RP': { name: "Rheinland-Pfalz", type: "Länder" },
  'DE-SH': { name: "Schleswig-Holstein", type: "Länder" },
  'DE-SL': { name: "Saarland", type: "Länder" },
  'DE-SN': { name: "Sachsen", type: "Länder" },
  'DE-ST': { name: "Sachsen-Anhalt", type: "Länder" },
  'DE-TH': { name: "Thüringen", type: "Länder" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
