// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'DJ';
export const countryName = "Djibouti";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'DJ-AR': { name: "Arta", type: "Region" },
  'DJ-AS': { name: "Ali Sabieh", type: "Region" },
  'DJ-DI': { name: "Dikhīl", type: "Region" },
  'DJ-DJ': { name: "Djibouti", type: "City" },
  'DJ-OB': { name: "Obock", type: "Region" },
  'DJ-TA': { name: "Tadjourah", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
