// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'DK';
export const countryName = "Denmark";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'DK-81': { name: "Nordjylland", type: "Region" },
  'DK-82': { name: "Midtjylland", type: "Region" },
  'DK-83': { name: "Syddanmark", type: "Region" },
  'DK-84': { name: "Hovedstaden", type: "Region" },
  'DK-85': { name: "Sjælland", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
