// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'DM';
export const countryName = "Dominica";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'DM-02': { name: "Saint Andrew", type: "Parish" },
  'DM-03': { name: "Saint David", type: "Parish" },
  'DM-04': { name: "Saint George", type: "Parish" },
  'DM-05': { name: "Saint John", type: "Parish" },
  'DM-06': { name: "Saint Joseph", type: "Parish" },
  'DM-07': { name: "Saint Luke", type: "Parish" },
  'DM-08': { name: "Saint Mark", type: "Parish" },
  'DM-09': { name: "Saint Patrick", type: "Parish" },
  'DM-10': { name: "Saint Paul", type: "Parish" },
  'DM-11': { name: "Saint Peter", type: "Parish" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
