// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'DO';
export const countryName = "Dominican Republic";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'DO-01': { name: "Distrito Nacional", type: "District" },
  'DO-02': { name: "Azua", type: "Province" },
  'DO-03': { name: "Baoruco", type: "Province" },
  'DO-04': { name: "Barahona", type: "Province" },
  'DO-05': { name: "Dajabón", type: "Province" },
  'DO-06': { name: "Duarte", type: "Province" },
  'DO-07': { name: "La Estrelleta", type: "Province" },
  'DO-08': { name: "El Seibo", type: "Province" },
  'DO-09': { name: "Espaillat", type: "Province" },
  'DO-10': { name: "Independencia", type: "Province" },
  'DO-11': { name: "La Altagracia", type: "Province" },
  'DO-12': { name: "La Romana", type: "Province" },
  'DO-13': { name: "La Vega", type: "Province" },
  'DO-14': { name: "María Trinidad Sánchez", type: "Province" },
  'DO-15': { name: "Monte Cristi", type: "Province" },
  'DO-16': { name: "Pedernales", type: "Province" },
  'DO-17': { name: "Peravia", type: "Province" },
  'DO-18': { name: "Puerto Plata", type: "Province" },
  'DO-19': { name: "Hermanas Mirabal", type: "Province" },
  'DO-20': { name: "Samaná", type: "Province" },
  'DO-21': { name: "San Cristóbal", type: "Province" },
  'DO-22': { name: "San Juan", type: "Province" },
  'DO-23': { name: "San Pedro de Macorís", type: "Province" },
  'DO-24': { name: "Sánchez Ramírez", type: "Province" },
  'DO-25': { name: "Santiago", type: "Province" },
  'DO-26': { name: "Santiago Rodríguez", type: "Province" },
  'DO-27': { name: "Valverde", type: "Province" },
  'DO-28': { name: "Monseñor Nouel", type: "Province" },
  'DO-29': { name: "Monte Plata", type: "Province" },
  'DO-30': { name: "Hato Mayor", type: "Province" },
  'DO-31': { name: "San José de Ocoa", type: "Province" },
  'DO-32': { name: "Santo Domingo", type: "Province" },
  'DO-33': { name: "Cibao Nordeste", type: "Region" },
  'DO-34': { name: "Cibao Noroeste", type: "Region" },
  'DO-35': { name: "Cibao Norte", type: "Region" },
  'DO-36': { name: "Cibao Sur", type: "Region" },
  'DO-37': { name: "El Valle", type: "Region" },
  'DO-38': { name: "Enriquillo", type: "Region" },
  'DO-39': { name: "Higuamo", type: "Region" },
  'DO-40': { name: "Ozama", type: "Region" },
  'DO-41': { name: "Valdesia", type: "Region" },
  'DO-42': { name: "Yuma", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
