// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'EC';
export const countryName = "Ecuador";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'EC-A': { name: "Azuay", type: "Province" },
  'EC-B': { name: "Bolívar", type: "Province" },
  'EC-C': { name: "Carchi", type: "Province" },
  'EC-D': { name: "Orellana", type: "Province" },
  'EC-E': { name: "Esmeraldas", type: "Province" },
  'EC-F': { name: "Cañar", type: "Province" },
  'EC-G': { name: "Guayas", type: "Province" },
  'EC-H': { name: "Chimborazo", type: "Province" },
  'EC-I': { name: "Imbabura", type: "Province" },
  'EC-L': { name: "Loja", type: "Province" },
  'EC-M': { name: "Manabí", type: "Province" },
  'EC-N': { name: "Napo", type: "Province" },
  'EC-O': { name: "El Oro", type: "Province" },
  'EC-P': { name: "Pichincha", type: "Province" },
  'EC-R': { name: "Los Ríos", type: "Province" },
  'EC-S': { name: "Morona-Santiago", type: "Province" },
  'EC-SD': { name: "Santo Domingo de los Tsáchilas", type: "Province" },
  'EC-SE': { name: "Santa Elena", type: "Province" },
  'EC-T': { name: "Tungurahua", type: "Province" },
  'EC-U': { name: "Sucumbíos", type: "Province" },
  'EC-W': { name: "Galápagos", type: "Province" },
  'EC-X': { name: "Cotopaxi", type: "Province" },
  'EC-Y': { name: "Pastaza", type: "Province" },
  'EC-Z': { name: "Zamora-Chinchipe", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
