// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'EE';
export const countryName = "Estonia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'EE-37': { name: "Harjumaa", type: "County" },
  'EE-39': { name: "Hiiumaa", type: "County" },
  'EE-44': { name: "Ida-Virumaa", type: "County" },
  'EE-49': { name: "Jõgevamaa", type: "County" },
  'EE-51': { name: "Järvamaa", type: "County" },
  'EE-57': { name: "Läänemaa", type: "County" },
  'EE-59': { name: "Lääne-Virumaa", type: "County" },
  'EE-65': { name: "Põlvamaa", type: "County" },
  'EE-67': { name: "Pärnumaa", type: "County" },
  'EE-70': { name: "Raplamaa", type: "County" },
  'EE-74': { name: "Saaremaa", type: "County" },
  'EE-78': { name: "Tartumaa", type: "County" },
  'EE-82': { name: "Valgamaa", type: "County" },
  'EE-84': { name: "Viljandimaa", type: "County" },
  'EE-86': { name: "Võrumaa", type: "County" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
