// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'EG';
export const countryName = "Egypt";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'EG-ALX': { name: "Al Iskandarīyah", type: "Governorate" },
  'EG-ASN': { name: "Aswān", type: "Governorate" },
  'EG-AST': { name: "Asyūţ", type: "Governorate" },
  'EG-BA': { name: "Al Baḩr al Aḩmar", type: "Governorate" },
  'EG-BH': { name: "Al Buḩayrah", type: "Governorate" },
  'EG-BNS': { name: "Banī Suwayf", type: "Governorate" },
  'EG-C': { name: "Al Qāhirah", type: "Governorate" },
  'EG-DK': { name: "Ad Daqahlīyah", type: "Governorate" },
  'EG-DT': { name: "Dumyāţ", type: "Governorate" },
  'EG-FYM': { name: "Al Fayyūm", type: "Governorate" },
  'EG-GH': { name: "Al Gharbīyah", type: "Governorate" },
  'EG-GZ': { name: "Al Jīzah", type: "Governorate" },
  'EG-IS': { name: "Al Ismā'īlīyah", type: "Governorate" },
  'EG-JS': { name: "Janūb Sīnā'", type: "Governorate" },
  'EG-KB': { name: "Al Qalyūbīyah", type: "Governorate" },
  'EG-KFS': { name: "Kafr ash Shaykh", type: "Governorate" },
  'EG-KN': { name: "Qinā", type: "Governorate" },
  'EG-LX': { name: "Al Uqşur", type: "Governorate" },
  'EG-MN': { name: "Al Minyā", type: "Governorate" },
  'EG-MNF': { name: "Al Minūfīyah", type: "Governorate" },
  'EG-MT': { name: "Maţrūḩ", type: "Governorate" },
  'EG-PTS': { name: "Būr Sa‘īd", type: "Governorate" },
  'EG-SHG': { name: "Sūhāj", type: "Governorate" },
  'EG-SHR': { name: "Ash Sharqīyah", type: "Governorate" },
  'EG-SIN': { name: "Shamāl Sīnā'", type: "Governorate" },
  'EG-SUZ': { name: "As Suways", type: "Governorate" },
  'EG-WAD': { name: "Al Wādī al Jadīd", type: "Governorate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
