// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'EH';
export const countryName = "Western Sahara";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'EH-EH': { name: "Western Sahara", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
