// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'ER';
export const countryName = "Eritrea";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'ER-AN': { name: "Ansabā", type: "Region" },
  'ER-DK': { name: "Debubawi K’eyyĭḥ Baḥri", type: "Region" },
  'ER-DU': { name: "Al Janūbī", type: "Region" },
  'ER-GB': { name: "Gash-Barka", type: "Region" },
  'ER-MA': { name: "Al Awsaţ", type: "Region" },
  'ER-SK': { name: "Semienawi K’eyyĭḥ Baḥri", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
