// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'ET';
export const countryName = "Ethiopia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'ET-AA': { name: "Addis Ababa", type: "Administration" },
  'ET-AF': { name: "Afar", type: "State" },
  'ET-AM': { name: "Amara", type: "State" },
  'ET-BE': { name: "Benshangul-Gumaz", type: "State" },
  'ET-DD': { name: "Dire Dawa", type: "Administration" },
  'ET-GA': { name: "Gambēla Hizboch", type: "State" },
  'ET-HA': { name: "Harari People", type: "State" },
  'ET-OR': { name: "Oromia", type: "State" },
  'ET-SN': { name: "Southern Nations, Nationalities and Peoples", type: "State" },
  'ET-SO': { name: "Somali", type: "State" },
  'ET-TI': { name: "Tigrai", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
