// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'FI';
export const countryName = "Finland";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'FI-01': { name: "Ahvenanmaan maakunta", type: "Region" },
  'FI-02': { name: "Etelä-Karjala", type: "Region" },
  'FI-03': { name: "Etelä-Pohjanmaa", type: "Region" },
  'FI-04': { name: "Etelä-Savo", type: "Region" },
  'FI-05': { name: "Kainuu", type: "Region" },
  'FI-06': { name: "Egentliga Tavastland", type: "Region" },
  'FI-07': { name: "Keski-Pohjanmaa", type: "Region" },
  'FI-08': { name: "Keski-Suomi", type: "Region" },
  'FI-09': { name: "Kymenlaakso", type: "Region" },
  'FI-10': { name: "Lappi", type: "Region" },
  'FI-11': { name: "Birkaland", type: "Region" },
  'FI-12': { name: "Österbotten", type: "Region" },
  'FI-13': { name: "Norra Karelen", type: "Region" },
  'FI-14': { name: "Norra Österbotten", type: "Region" },
  'FI-15': { name: "Norra Savolax", type: "Region" },
  'FI-16': { name: "Päijänne-Tavastland", type: "Region" },
  'FI-17': { name: "Satakunda", type: "Region" },
  'FI-18': { name: "Nyland", type: "Region" },
  'FI-19': { name: "Egentliga Finland", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
