// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'FJ';
export const countryName = "Fiji";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'FJ-01': { name: "Ba", type: "Province" },
  'FJ-02': { name: "Bua", type: "Province" },
  'FJ-03': { name: "Cakaudrove", type: "Province" },
  'FJ-04': { name: "Kadavu", type: "Province" },
  'FJ-05': { name: "Lau", type: "Province" },
  'FJ-06': { name: "Lomaiviti", type: "Province" },
  'FJ-07': { name: "Macuata", type: "Province" },
  'FJ-08': { name: "Nadroga and Navosa", type: "Province" },
  'FJ-09': { name: "Naitasiri", type: "Province" },
  'FJ-10': { name: "Namosi", type: "Province" },
  'FJ-11': { name: "Ra", type: "Province" },
  'FJ-12': { name: "Rewa", type: "Province" },
  'FJ-13': { name: "Serua", type: "Province" },
  'FJ-14': { name: "Tailevu", type: "Province" },
  'FJ-C': { name: "Central", type: "Division" },
  'FJ-E': { name: "Eastern", type: "Division" },
  'FJ-N': { name: "Northern", type: "Division" },
  'FJ-R': { name: "Rotuma", type: "Dependency" },
  'FJ-W': { name: "Western", type: "Division" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
