// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'FK';
export const countryName = "Falkland Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'FK-FK': { name: "Falkland Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
