// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'FM';
export const countryName = "Micronesia, Federated States Of";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'FM-KSA': { name: "Kosrae", type: "State" },
  'FM-PNI': { name: "Pohnpei", type: "State" },
  'FM-TRK': { name: "Chuuk", type: "State" },
  'FM-YAP': { name: "Yap", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
