// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'FO';
export const countryName = "Faroe Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'FO-FO': { name: "Faroe Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
