// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GA';
export const countryName = "Gabon";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GA-1': { name: "Estuaire", type: "Province" },
  'GA-2': { name: "Haut-Ogooué", type: "Province" },
  'GA-3': { name: "Moyen-Ogooué", type: "Province" },
  'GA-4': { name: "Ngounié", type: "Province" },
  'GA-5': { name: "Nyanga", type: "Province" },
  'GA-6': { name: "Ogooué-Ivindo", type: "Province" },
  'GA-7': { name: "Ogooué-Lolo", type: "Province" },
  'GA-8': { name: "Ogooué-Maritime", type: "Province" },
  'GA-9': { name: "Woleu-Ntem", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
