// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GD';
export const countryName = "Grenada";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GD-01': { name: "Saint Andrew", type: "Parish" },
  'GD-02': { name: "Saint David", type: "Parish" },
  'GD-03': { name: "Saint George", type: "Parish" },
  'GD-04': { name: "Saint John", type: "Parish" },
  'GD-05': { name: "Saint Mark", type: "Parish" },
  'GD-06': { name: "Saint Patrick", type: "Parish" },
  'GD-10': { name: "Southern Grenadine Islands", type: "Dependency" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
