// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GE';
export const countryName = "Georgia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GE-AB': { name: "Abkhazia", type: "Autonomous republic" },
  'GE-AJ': { name: "Ajaria", type: "Autonomous republic" },
  'GE-GU': { name: "Guria", type: "Region" },
  'GE-IM': { name: "Imereti", type: "Region" },
  'GE-KA': { name: "K'akheti", type: "Region" },
  'GE-KK': { name: "Kvemo Kartli", type: "Region" },
  'GE-MM': { name: "Mtskheta-Mtianeti", type: "Region" },
  'GE-RL': { name: "Rach'a-Lechkhumi-Kvemo Svaneti", type: "Region" },
  'GE-SJ': { name: "Samtskhe-Javakheti", type: "Region" },
  'GE-SK': { name: "Shida Kartli", type: "Region" },
  'GE-SZ': { name: "Samegrelo-Zemo Svaneti", type: "Region" },
  'GE-TB': { name: "Tbilisi", type: "City" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
