// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GF';
export const countryName = "French Guiana";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GF-GF': { name: "French Guiana", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
