// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GG';
export const countryName = "Guernsey";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GG-GG': { name: "Guernsey", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
