// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GH';
export const countryName = "Ghana";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GH-AA': { name: "Greater Accra", type: "Region" },
  'GH-AH': { name: "Ashanti", type: "Region" },
  'GH-BA': { name: "Brong-Ahafo", type: "Region" },
  'GH-CP': { name: "Central", type: "Region" },
  'GH-EP': { name: "Eastern", type: "Region" },
  'GH-NP': { name: "Northern", type: "Region" },
  'GH-TV': { name: "Volta", type: "Region" },
  'GH-UE': { name: "Upper East", type: "Region" },
  'GH-UW': { name: "Upper West", type: "Region" },
  'GH-WP': { name: "Western", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
