// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GI';
export const countryName = "Gibraltar";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GI-GI': { name: "Gibraltar", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
