// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GL';
export const countryName = "Greenland";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GL-KU': { name: "Kommune Kujalleq", type: "Municipality" },
  'GL-QA': { name: "Qaasuitsup Kommunia", type: "Municipality" },
  'GL-QE': { name: "Qeqqata Kommunia", type: "Municipality" },
  'GL-SM': { name: "Kommuneqarfik Sermersooq", type: "Municipality" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
