// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GM';
export const countryName = "Gambia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GM-B': { name: "Banjul", type: "City" },
  'GM-L': { name: "Lower River", type: "Division" },
  'GM-M': { name: "Central River", type: "Division" },
  'GM-N': { name: "North Bank", type: "Division" },
  'GM-U': { name: "Upper River", type: "Division" },
  'GM-W': { name: "Western", type: "Division" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
