// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GN';
export const countryName = "Guinea";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GN-B': { name: "Boké", type: "Administrative region" },
  'GN-BE': { name: "Beyla", type: "Prefecture" },
  'GN-BF': { name: "Boffa", type: "Prefecture" },
  'GN-BK': { name: "Boké", type: "Prefecture" },
  'GN-C': { name: "Conakry", type: "Governorate" },
  'GN-CO': { name: "Coyah", type: "Prefecture" },
  'GN-D': { name: "Kindia", type: "Administrative region" },
  'GN-DB': { name: "Dabola", type: "Prefecture" },
  'GN-DI': { name: "Dinguiraye", type: "Prefecture" },
  'GN-DL': { name: "Dalaba", type: "Prefecture" },
  'GN-DU': { name: "Dubréka", type: "Prefecture" },
  'GN-F': { name: "Faranah", type: "Administrative region" },
  'GN-FA': { name: "Faranah", type: "Prefecture" },
  'GN-FO': { name: "Forécariah", type: "Prefecture" },
  'GN-FR': { name: "Fria", type: "Prefecture" },
  'GN-GA': { name: "Gaoual", type: "Prefecture" },
  'GN-GU': { name: "Guékédou", type: "Prefecture" },
  'GN-K': { name: "Kankan", type: "Administrative region" },
  'GN-KA': { name: "Kankan", type: "Prefecture" },
  'GN-KB': { name: "Koubia", type: "Prefecture" },
  'GN-KD': { name: "Kindia", type: "Prefecture" },
  'GN-KE': { name: "Kérouané", type: "Prefecture" },
  'GN-KN': { name: "Koundara", type: "Prefecture" },
  'GN-KO': { name: "Kouroussa", type: "Prefecture" },
  'GN-KS': { name: "Kissidougou", type: "Prefecture" },
  'GN-L': { name: "Labé", type: "Administrative region" },
  'GN-LA': { name: "Labé", type: "Prefecture" },
  'GN-LE': { name: "Lélouma", type: "Prefecture" },
  'GN-LO': { name: "Lola", type: "Prefecture" },
  'GN-M': { name: "Mamou", type: "Administrative region" },
  'GN-MC': { name: "Macenta", type: "Prefecture" },
  'GN-MD': { name: "Mandiana", type: "Prefecture" },
  'GN-ML': { name: "Mali", type: "Prefecture" },
  'GN-MM': { name: "Mamou", type: "Prefecture" },
  'GN-N': { name: "Nzérékoré", type: "Administrative region" },
  'GN-NZ': { name: "Nzérékoré", type: "Prefecture" },
  'GN-PI': { name: "Pita", type: "Prefecture" },
  'GN-SI': { name: "Siguiri", type: "Prefecture" },
  'GN-TE': { name: "Télimélé", type: "Prefecture" },
  'GN-TO': { name: "Tougué", type: "Prefecture" },
  'GN-YO': { name: "Yomou", type: "Prefecture" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
