// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GP';
export const countryName = "Guadeloupe";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GP-GP': { name: "Guadeloupe", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
