// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GQ';
export const countryName = "Equatorial Guinea";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GQ-AN': { name: "Annobón", type: "Province" },
  'GQ-BN': { name: "Bioko Nord", type: "Province" },
  'GQ-BS': { name: "Bioko Sud", type: "Province" },
  'GQ-C': { name: "Região Continental", type: "Region" },
  'GQ-CS': { name: "Centro Sud", type: "Province" },
  'GQ-I': { name: "Região Insular", type: "Region" },
  'GQ-KN': { name: "Kié-Ntem", type: "Province" },
  'GQ-LI': { name: "Litoral", type: "Province" },
  'GQ-WN': { name: "Wele-Nzas", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
