// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GS';
export const countryName = "S.Georgia & S.Sandwich Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GS-GS': { name: "S.Georgia & S.Sandwich Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
