// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GT';
export const countryName = "Guatemala";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GT-AV': { name: "Alta Verapaz", type: "Department" },
  'GT-BV': { name: "Baja Verapaz", type: "Department" },
  'GT-CM': { name: "Chimaltenango", type: "Department" },
  'GT-CQ': { name: "Chiquimula", type: "Department" },
  'GT-ES': { name: "Escuintla", type: "Department" },
  'GT-GU': { name: "Guatemala", type: "Department" },
  'GT-HU': { name: "Huehuetenango", type: "Department" },
  'GT-IZ': { name: "Izabal", type: "Department" },
  'GT-JA': { name: "Jalapa", type: "Department" },
  'GT-JU': { name: "Jutiapa", type: "Department" },
  'GT-PE': { name: "Petén", type: "Department" },
  'GT-PR': { name: "El Progreso", type: "Department" },
  'GT-QC': { name: "Quiché", type: "Department" },
  'GT-QZ': { name: "Quetzaltenango", type: "Department" },
  'GT-RE': { name: "Retalhuleu", type: "Department" },
  'GT-SA': { name: "Sacatepéquez", type: "Department" },
  'GT-SM': { name: "San Marcos", type: "Department" },
  'GT-SO': { name: "Sololá", type: "Department" },
  'GT-SR': { name: "Santa Rosa", type: "Department" },
  'GT-SU': { name: "Suchitepéquez", type: "Department" },
  'GT-TO': { name: "Totonicapán", type: "Department" },
  'GT-ZA': { name: "Zacapa", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
