// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GU';
export const countryName = "Guam";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GU-GU': { name: "Guam", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
