// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GW';
export const countryName = "Guinea-Bissau";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GW-BA': { name: "Bafatá", type: "Region" },
  'GW-BL': { name: "Bolama", type: "Region" },
  'GW-BM': { name: "Biombo", type: "Region" },
  'GW-BS': { name: "Bissau", type: "Autonomous sector" },
  'GW-CA': { name: "Cacheu", type: "Region" },
  'GW-GA': { name: "Gabú", type: "Region" },
  'GW-L': { name: "Leste", type: "Province" },
  'GW-N': { name: "Norte", type: "Province" },
  'GW-OI': { name: "Oio", type: "Region" },
  'GW-QU': { name: "Quinara", type: "Region" },
  'GW-S': { name: "Sul", type: "Province" },
  'GW-TO': { name: "Tombali", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
