// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'GY';
export const countryName = "Guyana";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'GY-BA': { name: "Barima-Waini", type: "Region" },
  'GY-CU': { name: "Cuyuni-Mazaruni", type: "Region" },
  'GY-DE': { name: "Demerara-Mahaica", type: "Region" },
  'GY-EB': { name: "East Berbice-Corentyne", type: "Region" },
  'GY-ES': { name: "Essequibo Islands-West Demerara", type: "Region" },
  'GY-MA': { name: "Mahaica-Berbice", type: "Region" },
  'GY-PM': { name: "Pomeroon-Supenaam", type: "Region" },
  'GY-PT': { name: "Potaro-Siparuni", type: "Region" },
  'GY-UD': { name: "Upper Demerara-Berbice", type: "Region" },
  'GY-UT': { name: "Upper Takutu-Upper Essequibo", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
