// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'HK';
export const countryName = "Hong Kong";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'HK-HK': { name: "Hong Kong", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
