// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'HM';
export const countryName = "Heard & McDonald Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'HM-HM': { name: "Heard & McDonald Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
