// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'HN';
export const countryName = "Honduras";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'HN-AT': { name: "Atlántida", type: "Department" },
  'HN-CH': { name: "Choluteca", type: "Department" },
  'HN-CL': { name: "Colón", type: "Department" },
  'HN-CM': { name: "Comayagua", type: "Department" },
  'HN-CP': { name: "Copán", type: "Department" },
  'HN-CR': { name: "Cortés", type: "Department" },
  'HN-EP': { name: "El Paraíso", type: "Department" },
  'HN-FM': { name: "Francisco Morazán", type: "Department" },
  'HN-GD': { name: "Gracias a Dios", type: "Department" },
  'HN-IB': { name: "Islas de la Bahía", type: "Department" },
  'HN-IN': { name: "Intibucá", type: "Department" },
  'HN-LE': { name: "Lempira", type: "Department" },
  'HN-LP': { name: "La Paz", type: "Department" },
  'HN-OC': { name: "Ocotepeque", type: "Department" },
  'HN-OL': { name: "Olancho", type: "Department" },
  'HN-SB': { name: "Santa Bárbara", type: "Department" },
  'HN-VA': { name: "Valle", type: "Department" },
  'HN-YO': { name: "Yoro", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
