// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'HR';
export const countryName = "Croatia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'HR-01': { name: "Zagrebačka županija", type: "County" },
  'HR-02': { name: "Krapinsko-zagorska županija", type: "County" },
  'HR-03': { name: "Sisačko-moslavačka županija", type: "County" },
  'HR-04': { name: "Karlovačka županija", type: "County" },
  'HR-05': { name: "Varaždinska županija", type: "County" },
  'HR-06': { name: "Koprivničko-križevačka županija", type: "County" },
  'HR-07': { name: "Bjelovarsko-bilogorska županija", type: "County" },
  'HR-08': { name: "Primorsko-goranska županija", type: "County" },
  'HR-09': { name: "Ličko-senjska županija", type: "County" },
  'HR-10': { name: "Virovitičko-podravska županija", type: "County" },
  'HR-11': { name: "Požeško-slavonska županija", type: "County" },
  'HR-12': { name: "Brodsko-posavska županija", type: "County" },
  'HR-13': { name: "Zadarska županija", type: "County" },
  'HR-14': { name: "Osječko-baranjska županija", type: "County" },
  'HR-15': { name: "Šibensko-kninska županija", type: "County" },
  'HR-16': { name: "Vukovarsko-srijemska županija", type: "County" },
  'HR-17': { name: "Splitsko-dalmatinska županija", type: "County" },
  'HR-18': { name: "Istarska županija", type: "County" },
  'HR-19': { name: "Dubrovačko-neretvanska županija", type: "County" },
  'HR-20': { name: "Međimurska županija", type: "County" },
  'HR-21': { name: "Grad Zagreb", type: "City" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
