// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'HT';
export const countryName = "Haiti";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'HT-AR': { name: "Artibonite", type: "Department" },
  'HT-CE': { name: "Centre", type: "Department" },
  'HT-GA': { name: "Grandans", type: "Department" },
  'HT-ND': { name: "Nò", type: "Department" },
  'HT-NE': { name: "Nòdès", type: "Department" },
  'HT-NI': { name: "Nip", type: "Department" },
  'HT-NO': { name: "Nòdwès", type: "Department" },
  'HT-OU': { name: "Lwès", type: "Department" },
  'HT-SD': { name: "Sid", type: "Department" },
  'HT-SE': { name: "Sidès", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
