// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'HU';
export const countryName = "Hungary";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'HU-BA': { name: "Baranya", type: "County" },
  'HU-BC': { name: "Békéscsaba", type: "City of county right" },
  'HU-BE': { name: "Békés", type: "County" },
  'HU-BK': { name: "Bács-Kiskun", type: "County" },
  'HU-BU': { name: "Budapest", type: "Capital city" },
  'HU-BZ': { name: "Borsod-Abaúj-Zemplén", type: "County" },
  'HU-CS': { name: "Csongrád", type: "County" },
  'HU-DE': { name: "Debrecen", type: "City of county right" },
  'HU-DU': { name: "Dunaújváros", type: "City of county right" },
  'HU-EG': { name: "Eger", type: "City of county right" },
  'HU-ER': { name: "Érd", type: "City of county right" },
  'HU-FE': { name: "Fejér", type: "County" },
  'HU-GS': { name: "Győr-Moson-Sopron", type: "County" },
  'HU-GY': { name: "Győr", type: "City of county right" },
  'HU-HB': { name: "Hajdú-Bihar", type: "County" },
  'HU-HE': { name: "Heves", type: "County" },
  'HU-HV': { name: "Hódmezővásárhely", type: "City of county right" },
  'HU-JN': { name: "Jász-Nagykun-Szolnok", type: "County" },
  'HU-KE': { name: "Komárom-Esztergom", type: "County" },
  'HU-KM': { name: "Kecskemét", type: "City of county right" },
  'HU-KV': { name: "Kaposvár", type: "City of county right" },
  'HU-MI': { name: "Miskolc", type: "City of county right" },
  'HU-NK': { name: "Nagykanizsa", type: "City of county right" },
  'HU-NO': { name: "Nógrád", type: "County" },
  'HU-NY': { name: "Nyíregyháza", type: "City of county right" },
  'HU-PE': { name: "Pest", type: "County" },
  'HU-PS': { name: "Pécs", type: "City of county right" },
  'HU-SD': { name: "Szeged", type: "City of county right" },
  'HU-SF': { name: "Székesfehérvár", type: "City of county right" },
  'HU-SH': { name: "Szombathely", type: "City of county right" },
  'HU-SK': { name: "Szolnok", type: "City of county right" },
  'HU-SN': { name: "Sopron", type: "City of county right" },
  'HU-SO': { name: "Somogy", type: "County" },
  'HU-SS': { name: "Szekszárd", type: "City of county right" },
  'HU-ST': { name: "Salgótarján", type: "City of county right" },
  'HU-SZ': { name: "Szabolcs-Szatmár-Bereg", type: "County" },
  'HU-TB': { name: "Tatabánya", type: "City of county right" },
  'HU-TO': { name: "Tolna", type: "County" },
  'HU-VA': { name: "Vas", type: "County" },
  'HU-VE': { name: "Veszprém", type: "County" },
  'HU-VM': { name: "Veszprém", type: "City of county right" },
  'HU-ZA': { name: "Zala", type: "County" },
  'HU-ZE': { name: "Zalaegerszeg", type: "City of county right" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
