// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'ID';
export const countryName = "Indonesia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'ID-AC': { name: "Aceh", type: "Autonomous province" },
  'ID-BA': { name: "Bali", type: "Province" },
  'ID-BB': { name: "Bangka Belitung", type: "Province" },
  'ID-BE': { name: "Bengkulu", type: "Province" },
  'ID-BT': { name: "Banten", type: "Province" },
  'ID-GO': { name: "Gorontalo", type: "Province" },
  'ID-JA': { name: "Jambi", type: "Province" },
  'ID-JB': { name: "Jawa Barat", type: "Province" },
  'ID-JI': { name: "Jawa Timur", type: "Province" },
  'ID-JK': { name: "Jakarta Raya", type: "Special district" },
  'ID-JT': { name: "Jawa Tengah", type: "Province" },
  'ID-JW': { name: "Jawa", type: "Geographical unit" },
  'ID-KA': { name: "Kalimantan", type: "Geographical unit" },
  'ID-KB': { name: "Kalimantan Barat", type: "Province" },
  'ID-KI': { name: "Kalimantan Timur", type: "Province" },
  'ID-KR': { name: "Kepulauan Riau", type: "Province" },
  'ID-KS': { name: "Kalimantan Selatan", type: "Province" },
  'ID-KT': { name: "Kalimantan Tengah", type: "Province" },
  'ID-KU': { name: "Kalimantan Utara", type: "Province" },
  'ID-LA': { name: "Lampung", type: "Province" },
  'ID-MA': { name: "Maluku", type: "Province" },
  'ID-ML': { name: "Maluku", type: "Geographical unit" },
  'ID-MU': { name: "Maluku Utara", type: "Province" },
  'ID-NB': { name: "Nusa Tenggara Barat", type: "Province" },
  'ID-NT': { name: "Nusa Tenggara Timur", type: "Province" },
  'ID-NU': { name: "Nusa Tenggara", type: "Geographical unit" },
  'ID-PA': { name: "Papua", type: "Province" },
  'ID-PB': { name: "Papua Barat", type: "Province" },
  'ID-PD': { name: "Papua Barat Daya", type: "Province" },
  'ID-PE': { name: "Papua Pegunungan", type: "Province" },
  'ID-PP': { name: "Papua", type: "Geographical unit" },
  'ID-PS': { name: "Papua Selatan", type: "Province" },
  'ID-PT': { name: "Papua Tengah", type: "Province" },
  'ID-RI': { name: "Riau", type: "Province" },
  'ID-SA': { name: "Sulawesi Utara", type: "Province" },
  'ID-SB': { name: "Sumatera Barat", type: "Province" },
  'ID-SG': { name: "Sulawesi Tenggara", type: "Province" },
  'ID-SL': { name: "Sulawesi", type: "Geographical unit" },
  'ID-SM': { name: "Sumatera", type: "Geographical unit" },
  'ID-SN': { name: "Sulawesi Selatan", type: "Province" },
  'ID-SR': { name: "Sulawesi Barat", type: "Province" },
  'ID-SS': { name: "Sumatera Selatan", type: "Province" },
  'ID-ST': { name: "Sulawesi Tengah", type: "Province" },
  'ID-SU': { name: "Sumatera Utara", type: "Province" },
  'ID-YO': { name: "Yogyakarta", type: "Special region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
