// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'IE';
export const countryName = "Ireland";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'IE-C': { name: "Connacht", type: "Province" },
  'IE-CE': { name: "An Clár", type: "County" },
  'IE-CN': { name: "An Cabhán", type: "County" },
  'IE-CO': { name: "Corcaigh", type: "County" },
  'IE-CW': { name: "Carlow", type: "County" },
  'IE-D': { name: "Baile Átha Cliath", type: "County" },
  'IE-DL': { name: "Donegal", type: "County" },
  'IE-G': { name: "Gaillimh", type: "County" },
  'IE-KE': { name: "Cill Dara", type: "County" },
  'IE-KK': { name: "Cill Chainnigh", type: "County" },
  'IE-KY': { name: "Ciarraí", type: "County" },
  'IE-L': { name: "Laighin", type: "Province" },
  'IE-LD': { name: "An Longfort", type: "County" },
  'IE-LH': { name: "Louth", type: "County" },
  'IE-LK': { name: "Limerick", type: "County" },
  'IE-LM': { name: "Leitrim", type: "County" },
  'IE-LS': { name: "Laois", type: "County" },
  'IE-M': { name: "An Mhumhain", type: "Province" },
  'IE-MH': { name: "An Mhí", type: "County" },
  'IE-MN': { name: "Monaghan", type: "County" },
  'IE-MO': { name: "Maigh Eo", type: "County" },
  'IE-OY': { name: "Offaly", type: "County" },
  'IE-RN': { name: "Ros Comáin", type: "County" },
  'IE-SO': { name: "Sligeach", type: "County" },
  'IE-TA': { name: "Tiobraid Árann", type: "County" },
  'IE-U': { name: "Ulaidh", type: "Province" },
  'IE-WD': { name: "Port Láirge", type: "County" },
  'IE-WH': { name: "An Iarmhí", type: "County" },
  'IE-WW': { name: "Cill Mhantáin", type: "County" },
  'IE-WX': { name: "Loch Garman", type: "County" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
