// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'IL';
export const countryName = "Israel";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'IL-D': { name: "Southern District", type: "District" },
  'IL-HA': { name: "Haifa", type: "District" },
  'IL-JM': { name: "Jerusalem", type: "District" },
  'IL-M': { name: "Central District", type: "District" },
  'IL-TA': { name: "Tel Aviv", type: "District" },
  'IL-Z': { name: "Northern District", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
