// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'IM';
export const countryName = "Isle of Man";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'IM-IM': { name: "Isle of Main", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
