// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'IN';
export const countryName = "India";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'IN-AN': { name: "Andaman and Nicobar Islands", type: "Union territory" },
  'IN-AP': { name: "Andhra Pradesh", type: "State" },
  'IN-AR': { name: "Arunachal Pradesh", type: "State" },
  'IN-AS': { name: "Assam", type: "State" },
  'IN-BR': { name: "Bihar", type: "State" },
  'IN-CH': { name: "Chandigarh", type: "Union territory" },
  'IN-CT': { name: "Chhattisgarh", type: "State" },
  'IN-DH': { name: "Dadra and Nagar Haveli and Daman and Diu", type: "Union territory" },
  'IN-DL': { name: "Delhi", type: "Union territory" },
  'IN-GA': { name: "Goa", type: "State" },
  'IN-GJ': { name: "Gujarat", type: "State" },
  'IN-HP': { name: "Himachal Pradesh", type: "State" },
  'IN-HR': { name: "Haryana", type: "State" },
  'IN-JH': { name: "Jharkhand", type: "State" },
  'IN-JK': { name: "Jammu and Kashmir", type: "Union territory" },
  'IN-KA': { name: "Karnataka", type: "State" },
  'IN-KL': { name: "Kerala", type: "State" },
  'IN-LA': { name: "Ladakh", type: "Union territory" },
  'IN-LD': { name: "Lakshadweep", type: "Union territory" },
  'IN-MH': { name: "Maharashtra", type: "State" },
  'IN-ML': { name: "Meghalaya", type: "State" },
  'IN-MN': { name: "Manipur", type: "State" },
  'IN-MP': { name: "Madhya Pradesh", type: "State" },
  'IN-MZ': { name: "Mizoram", type: "State" },
  'IN-NL': { name: "Nagaland", type: "State" },
  'IN-OR': { name: "Odisha", type: "State" },
  'IN-PB': { name: "Punjab", type: "State" },
  'IN-PY': { name: "Puducherry", type: "Union territory" },
  'IN-RJ': { name: "Rajasthan", type: "State" },
  'IN-SK': { name: "Sikkim", type: "State" },
  'IN-TG': { name: "Telangana", type: "State" },
  'IN-TN': { name: "Tamil Nadu", type: "State" },
  'IN-TR': { name: "Tripura", type: "State" },
  'IN-UP': { name: "Uttar Pradesh", type: "State" },
  'IN-UT': { name: "Uttarakhand", type: "State" },
  'IN-WB': { name: "West Bengal", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
