// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'IO';
export const countryName = "British Indian Ocean Territory";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'IO-IO': { name: "British Indian Ocean Territory", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
