// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'IQ';
export const countryName = "Iraq";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'IQ-AN': { name: "Al Anbār", type: "Governorate" },
  'IQ-AR': { name: "Arbīl", type: "Governorate" },
  'IQ-BA': { name: "Al Başrah", type: "Governorate" },
  'IQ-BB': { name: "Bābil", type: "Governorate" },
  'IQ-BG': { name: "Baghdād", type: "Governorate" },
  'IQ-DA': { name: "Dahūk", type: "Governorate" },
  'IQ-DI': { name: "Diyālá", type: "Governorate" },
  'IQ-DQ': { name: "Dhī Qār", type: "Governorate" },
  'IQ-HA': { name: "Halabja", type: "Governorate" },
  'IQ-KA': { name: "Karbalā'", type: "Governorate" },
  'IQ-KI': { name: "Kirkūk", type: "Governorate" },
  'IQ-MA': { name: "Maysān", type: "Governorate" },
  'IQ-MU': { name: "Al Muthanná", type: "Governorate" },
  'IQ-NA': { name: "An Najaf", type: "Governorate" },
  'IQ-NI': { name: "Nīnawá", type: "Governorate" },
  'IQ-QA': { name: "Al Qādisīyah", type: "Governorate" },
  'IQ-SD': { name: "Şalāḩ ad Dīn", type: "Governorate" },
  'IQ-SU': { name: "As Sulaymānīyah", type: "Governorate" },
  'IQ-WA': { name: "Wāsiţ", type: "Governorate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
