// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'IR';
export const countryName = "Iran";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'IR-01': { name: "Āz̄arbāyjān-e Sharqī", type: "Province" },
  'IR-02': { name: "Āz̄arbāyjān-e Gharbī", type: "Province" },
  'IR-03': { name: "Ardabīl", type: "Province" },
  'IR-04': { name: "Eşfahān", type: "Province" },
  'IR-05': { name: "Īlām", type: "Province" },
  'IR-06': { name: "Būshehr", type: "Province" },
  'IR-07': { name: "Tehrān", type: "Province" },
  'IR-08': { name: "Chahār Maḩāll va Bakhtīārī", type: "Province" },
  'IR-10': { name: "Khūzestān", type: "Province" },
  'IR-11': { name: "Zanjān", type: "Province" },
  'IR-12': { name: "Semnān", type: "Province" },
  'IR-13': { name: "Sīstān va Balūchestān", type: "Province" },
  'IR-14': { name: "Fārs", type: "Province" },
  'IR-15': { name: "Kermān", type: "Province" },
  'IR-16': { name: "Kordestān", type: "Province" },
  'IR-17': { name: "Kermānshāh", type: "Province" },
  'IR-18': { name: "Kohgīlūyeh va Būyer Aḩmad", type: "Province" },
  'IR-19': { name: "Gīlān", type: "Province" },
  'IR-20': { name: "Lorestān", type: "Province" },
  'IR-21': { name: "Māzandarān", type: "Province" },
  'IR-22': { name: "Markazī", type: "Province" },
  'IR-23': { name: "Hormozgān", type: "Province" },
  'IR-24': { name: "Hamadān", type: "Province" },
  'IR-25': { name: "Yazd", type: "Province" },
  'IR-26': { name: "Qom", type: "Province" },
  'IR-27': { name: "Golestān", type: "Province" },
  'IR-28': { name: "Qazvīn", type: "Province" },
  'IR-29': { name: "Khorāsān-e Janūbī", type: "Province" },
  'IR-30': { name: "Khorāsān-e Razavī", type: "Province" },
  'IR-31': { name: "Khorāsān-e Shemālī", type: "Province" },
  'IR-32': { name: "Alborz", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
