// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'IS';
export const countryName = "Iceland";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'IS-0': { name: "Reykjavík", type: "Region" },
  'IS-1': { name: "Höfuðborgarsvæði utan Reykjavíkur", type: "Region" },
  'IS-2': { name: "Suðurnes", type: "Region" },
  'IS-3': { name: "Vesturland", type: "Region" },
  'IS-4': { name: "Vestfirðir", type: "Region" },
  'IS-5': { name: "Norðurland vestra", type: "Region" },
  'IS-6': { name: "Norðurland eystra", type: "Region" },
  'IS-7': { name: "Austurland", type: "Region" },
  'IS-8': { name: "Suðurland", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
