// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'JE';
export const countryName = "Jersey";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'JE-JE': { name: "Jersey", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
