// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'JM';
export const countryName = "Jamaica";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'JM-01': { name: "Kingston", type: "Parish" },
  'JM-02': { name: "Saint Andrew", type: "Parish" },
  'JM-03': { name: "Saint Thomas", type: "Parish" },
  'JM-04': { name: "Portland", type: "Parish" },
  'JM-05': { name: "Saint Mary", type: "Parish" },
  'JM-06': { name: "Saint Ann", type: "Parish" },
  'JM-07': { name: "Trelawny", type: "Parish" },
  'JM-08': { name: "Saint James", type: "Parish" },
  'JM-09': { name: "Hanover", type: "Parish" },
  'JM-10': { name: "Westmoreland", type: "Parish" },
  'JM-11': { name: "Saint Elizabeth", type: "Parish" },
  'JM-12': { name: "Manchester", type: "Parish" },
  'JM-13': { name: "Clarendon", type: "Parish" },
  'JM-14': { name: "Saint Catherine", type: "Parish" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
