// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'JO';
export const countryName = "Jordan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'JO-AJ': { name: "ʽAjlūn", type: "Governorate" },
  'JO-AM': { name: "‘Ammān", type: "Governorate" },
  'JO-AQ': { name: "Al ʽAqabah", type: "Governorate" },
  'JO-AT': { name: "Aţ Ţafīlah", type: "Governorate" },
  'JO-AZ': { name: "Az Zarqā'", type: "Governorate" },
  'JO-BA': { name: "Al Balqā'", type: "Governorate" },
  'JO-IR': { name: "Irbid", type: "Governorate" },
  'JO-JA': { name: "Jarash", type: "Governorate" },
  'JO-KA': { name: "Al Karak", type: "Governorate" },
  'JO-MA': { name: "Al Mafraq", type: "Governorate" },
  'JO-MD': { name: "Mādabā", type: "Governorate" },
  'JO-MN': { name: "Ma'ān", type: "Governorate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
