// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'JP';
export const countryName = "Japan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'JP-01': { name: "Hokkaido", type: "Prefecture" },
  'JP-02': { name: "Aomori", type: "Prefecture" },
  'JP-03': { name: "Iwate", type: "Prefecture" },
  'JP-04': { name: "Miyagi", type: "Prefecture" },
  'JP-05': { name: "Akita", type: "Prefecture" },
  'JP-06': { name: "Yamagata", type: "Prefecture" },
  'JP-07': { name: "Fukushima", type: "Prefecture" },
  'JP-08': { name: "Ibaraki", type: "Prefecture" },
  'JP-09': { name: "Tochigi", type: "Prefecture" },
  'JP-10': { name: "Gunma", type: "Prefecture" },
  'JP-11': { name: "Saitama", type: "Prefecture" },
  'JP-12': { name: "Chiba", type: "Prefecture" },
  'JP-13': { name: "Tôkyô", type: "Prefecture" },
  'JP-14': { name: "Kanagawa", type: "Prefecture" },
  'JP-15': { name: "Niigata", type: "Prefecture" },
  'JP-16': { name: "Toyama", type: "Prefecture" },
  'JP-17': { name: "Ishikawa", type: "Prefecture" },
  'JP-18': { name: "Fukui", type: "Prefecture" },
  'JP-19': { name: "Yamanashi", type: "Prefecture" },
  'JP-20': { name: "Nagano", type: "Prefecture" },
  'JP-21': { name: "Gifu", type: "Prefecture" },
  'JP-22': { name: "Shizuoka", type: "Prefecture" },
  'JP-23': { name: "Aichi", type: "Prefecture" },
  'JP-24': { name: "Mie", type: "Prefecture" },
  'JP-25': { name: "Shiga", type: "Prefecture" },
  'JP-26': { name: "Kyoto", type: "Prefecture" },
  'JP-27': { name: "Osaka", type: "Prefecture" },
  'JP-28': { name: "Hyogo", type: "Prefecture" },
  'JP-29': { name: "Nara", type: "Prefecture" },
  'JP-30': { name: "Wakayama", type: "Prefecture" },
  'JP-31': { name: "Tottori", type: "Prefecture" },
  'JP-32': { name: "Shimane", type: "Prefecture" },
  'JP-33': { name: "Okayama", type: "Prefecture" },
  'JP-34': { name: "Hiroshima", type: "Prefecture" },
  'JP-35': { name: "Yamaguchi", type: "Prefecture" },
  'JP-36': { name: "Tokushima", type: "Prefecture" },
  'JP-37': { name: "Kagawa", type: "Prefecture" },
  'JP-38': { name: "Ehime", type: "Prefecture" },
  'JP-39': { name: "Kochi", type: "Prefecture" },
  'JP-40': { name: "Fukuoka", type: "Prefecture" },
  'JP-41': { name: "Saga", type: "Prefecture" },
  'JP-42': { name: "Nagasaki", type: "Prefecture" },
  'JP-43': { name: "Kumamoto", type: "Prefecture" },
  'JP-44': { name: "Oita", type: "Prefecture" },
  'JP-45': { name: "Miyazaki", type: "Prefecture" },
  'JP-46': { name: "Kagoshima", type: "Prefecture" },
  'JP-47': { name: "Okinawa", type: "Prefecture" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
