// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'KG';
export const countryName = "Kyrgyzstan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'KG-B': { name: "Batken", type: "Region" },
  'KG-C': { name: "Chü", type: "Region" },
  'KG-GB': { name: "Bishkek", type: "City" },
  'KG-GO': { name: "Gorod Oš", type: "City" },
  'KG-J': { name: "Džalal-Abadskaja oblast'", type: "Region" },
  'KG-N': { name: "Naryn", type: "Region" },
  'KG-O': { name: "Osh", type: "Region" },
  'KG-T': { name: "Talas", type: "Region" },
  'KG-Y': { name: "Issyk-Kul'skaja oblast'", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
