// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'KH';
export const countryName = "Cambodia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'KH-1': { name: "Bântéay Méanchey", type: "Province" },
  'KH-10': { name: "Krâchéh", type: "Province" },
  'KH-11': { name: "Môndól Kiri", type: "Province" },
  'KH-12': { name: "Phnom Penh", type: "Autonomous municipality" },
  'KH-13': { name: "Preăh Vihéar", type: "Province" },
  'KH-14': { name: "Prey Veaeng", type: "Province" },
  'KH-15': { name: "Pousaat", type: "Province" },
  'KH-16': { name: "Rotanak Kiri", type: "Province" },
  'KH-17': { name: "Siem Reab", type: "Province" },
  'KH-18': { name: "Krŏng Preăh Sihanouk", type: "Autonomous municipality" },
  'KH-19': { name: "Stoĕng Trêng", type: "Province" },
  'KH-2': { name: "Baat Dambang", type: "Province" },
  'KH-20': { name: "Svaay Rieng", type: "Province" },
  'KH-21': { name: "Taakaev", type: "Province" },
  'KH-22': { name: "Ŏtdâr Méanchey", type: "Province" },
  'KH-23': { name: "Krong Kaeb", type: "Autonomous municipality" },
  'KH-24': { name: "Krŏng Pailĭn", type: "Autonomous municipality" },
  'KH-3': { name: "Kampong Chaam", type: "Province" },
  'KH-4': { name: "Kampong Chhnang", type: "Province" },
  'KH-5': { name: "Kâmpóng Spœ", type: "Province" },
  'KH-6': { name: "Kâmpóng Thum", type: "Province" },
  'KH-7': { name: "Kampot", type: "Province" },
  'KH-8': { name: "Kandaal", type: "Province" },
  'KH-9': { name: "Kaoh Kong", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
