// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'KI';
export const countryName = "Kiribati";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'KI-G': { name: "Gilbert Islands", type: "Group of islands" },
  'KI-L': { name: "Line Islands", type: "Group of islands" },
  'KI-P': { name: "Phoenix Islands", type: "Group of islands" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
