// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'KM';
export const countryName = "Comoros";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'KM-A': { name: "Andjouân", type: "Island" },
  'KM-G': { name: "Andjazîdja", type: "Island" },
  'KM-M': { name: "Mohéli", type: "Island" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
