// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'KN';
export const countryName = "Saint Kitts And Nevis";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'KN-01': { name: "Christ Church Nichola Town", type: "Parish" },
  'KN-02': { name: "Saint Anne Sandy Point", type: "Parish" },
  'KN-03': { name: "Saint George Basseterre", type: "Parish" },
  'KN-04': { name: "Saint George Gingerland", type: "Parish" },
  'KN-05': { name: "Saint James Windward", type: "Parish" },
  'KN-06': { name: "Saint John Capisterre", type: "Parish" },
  'KN-07': { name: "Saint John Figtree", type: "Parish" },
  'KN-08': { name: "Saint Mary Cayon", type: "Parish" },
  'KN-09': { name: "Saint Paul Capisterre", type: "Parish" },
  'KN-10': { name: "Saint Paul Charlestown", type: "Parish" },
  'KN-11': { name: "Saint Peter Basseterre", type: "Parish" },
  'KN-12': { name: "Saint Thomas Lowland", type: "Parish" },
  'KN-13': { name: "Saint Thomas Middle Island", type: "Parish" },
  'KN-15': { name: "Trinity Palmetto Point", type: "Parish" },
  'KN-K': { name: "Saint Kitts", type: "State" },
  'KN-N': { name: "Nevis", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
