// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'KP';
export const countryName = "Korea, Democratic People's Republic Of";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'KP-01': { name: "P'yǒngyang", type: "Capital city" },
  'KP-02': { name: "P'yǒngan-namdo", type: "Province" },
  'KP-03': { name: "P'yǒngan-bukto", type: "Province" },
  'KP-04': { name: "Chagang-do", type: "Province" },
  'KP-05': { name: "Hwanghae-namdo", type: "Province" },
  'KP-06': { name: "Hwanghae-bukto", type: "Province" },
  'KP-07': { name: "Kangweonto", type: "Province" },
  'KP-08': { name: "Hamgyǒng-namdo", type: "Province" },
  'KP-09': { name: "Hamgyǒng-bukto", type: "Province" },
  'KP-10': { name: "Ryangkangto", type: "Province" },
  'KP-13': { name: "Nasǒn", type: "Special city" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
