// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'KR';
export const countryName = "Korea, Republic of";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'KR-11': { name: "Seoul-T'ǔkpyǒlshi", type: "Special city" },
  'KR-26': { name: "Busan Gwang'yeogsi", type: "Metropolitan city" },
  'KR-27': { name: "Daegu Gwang'yeogsi", type: "Metropolitan city" },
  'KR-28': { name: "Inch'ǒn-Kwangyǒkshi", type: "Metropolitan city" },
  'KR-29': { name: "Gwangju Gwang'yeogsi", type: "Metropolitan city" },
  'KR-30': { name: "Daejeon Gwang'yeogsi", type: "Metropolitan city" },
  'KR-31': { name: "Ulsan Gwang'yeogsi", type: "Metropolitan city" },
  'KR-41': { name: "Gyeonggido", type: "Province" },
  'KR-42': { name: "Gang'weondo", type: "Province" },
  'KR-43': { name: "Ch'ungch'ǒngbuk-do", type: "Province" },
  'KR-44': { name: "Ch'ungch'ǒngnam-do", type: "Province" },
  'KR-45': { name: "Chǒllabuk-do", type: "Province" },
  'KR-46': { name: "Chǒllanam-do", type: "Province" },
  'KR-47': { name: "Gyeongsangbugdo", type: "Province" },
  'KR-48': { name: "Gyeongsangnamdo", type: "Province" },
  'KR-49': { name: "Cheju-do", type: "Special self-governing province" },
  'KR-50': { name: "Sejong", type: "Special self-governing city" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
