// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'KW';
export const countryName = "Kuwait";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'KW-AH': { name: "Al Aḩmadī", type: "Governorate" },
  'KW-FA': { name: "Al Farwānīyah", type: "Governorate" },
  'KW-HA': { name: "Ḩawallī", type: "Governorate" },
  'KW-JA': { name: "Al Jahrā’", type: "Governorate" },
  'KW-KU': { name: "Al Kuwayt", type: "Governorate" },
  'KW-MU': { name: "Mubārak al Kabīr", type: "Governorate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
