// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'KY';
export const countryName = "Cayman Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'KY-KY': { name: "Cayman Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
