// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'KZ';
export const countryName = "Kazakhstan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'KZ-ABY': { name: "Abai oblysy", type: "Region" },
  'KZ-AKM': { name: "Akmolinskaja oblast'", type: "Region" },
  'KZ-AKT': { name: "Aktjubinskaja oblast'", type: "Region" },
  'KZ-ALA': { name: "Almaty", type: "City" },
  'KZ-ALM': { name: "Almatinskaja oblast'", type: "Region" },
  'KZ-AST': { name: "Astana", type: "City" },
  'KZ-ATY': { name: "Atyraū oblysy", type: "Region" },
  'KZ-KAR': { name: "Karagandinskaja oblast'", type: "Region" },
  'KZ-KUS': { name: "Kostanajskaja oblast'", type: "Region" },
  'KZ-KZY': { name: "Kyzylordinskaja oblast'", type: "Region" },
  'KZ-MAN': { name: "Mangghystaū oblysy", type: "Region" },
  'KZ-PAV': { name: "Pavlodar oblysy", type: "Region" },
  'KZ-SEV': { name: "Severo-Kazahstanskaja oblast'", type: "Region" },
  'KZ-SHY': { name: "Shymkent", type: "City" },
  'KZ-TUR': { name: "Turkistan oblysy", type: "Region" },
  'KZ-ULY': { name: "Ulytau oblysy", type: "Region" },
  'KZ-VOS': { name: "Shyghys Qazaqstan oblysy", type: "Region" },
  'KZ-ZAP': { name: "Batys Qazaqstan oblysy", type: "Region" },
  'KZ-ZHA': { name: "Zhambyl oblysy", type: "Region" },
  'KZ-ZHE': { name: "Zhetysu oblysy", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
