// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'LA';
export const countryName = "Laos";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'LA-AT': { name: "Attapu", type: "Province" },
  'LA-BK': { name: "Bokèo", type: "Province" },
  'LA-BL': { name: "Bolikhamxai", type: "Province" },
  'LA-CH': { name: "Champasak", type: "Province" },
  'LA-HO': { name: "Houaphan", type: "Province" },
  'LA-KH': { name: "Khammouan", type: "Province" },
  'LA-LM': { name: "Louang Namtha", type: "Province" },
  'LA-LP': { name: "Louangphabang", type: "Province" },
  'LA-OU': { name: "Oudomsai", type: "Province" },
  'LA-PH': { name: "Phôngsali", type: "Province" },
  'LA-SL': { name: "Salavan", type: "Province" },
  'LA-SV': { name: "Savannakhét", type: "Province" },
  'LA-VI': { name: "Vientiane", type: "Province" },
  'LA-VT': { name: "Vientiane", type: "Prefecture" },
  'LA-XA': { name: "Sayaboury", type: "Province" },
  'LA-XE': { name: "Sékong", type: "Province" },
  'LA-XI': { name: "Xiangkhouang", type: "Province" },
  'LA-XN': { name: "Xaisômboun", type: "Special zone" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
