// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'LB';
export const countryName = "Lebanon";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'LB-AK': { name: "Aakkâr", type: "Governorate" },
  'LB-AS': { name: "Ash Shimāl", type: "Governorate" },
  'LB-BA': { name: "Bayrūt", type: "Governorate" },
  'LB-BH': { name: "Baalbek-Hermel", type: "Governorate" },
  'LB-BI': { name: "Al Biqā‘", type: "Governorate" },
  'LB-JA': { name: "Al Janūb", type: "Governorate" },
  'LB-JL': { name: "Jabal Lubnān", type: "Governorate" },
  'LB-NA': { name: "An Nabaţīyah", type: "Governorate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
