// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'LC';
export const countryName = "Saint Lucia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'LC-01': { name: "Anse la Raye", type: "District" },
  'LC-02': { name: "Castries", type: "District" },
  'LC-03': { name: "Choiseul", type: "District" },
  'LC-05': { name: "Dennery", type: "District" },
  'LC-06': { name: "Gros Islet", type: "District" },
  'LC-07': { name: "Laborie", type: "District" },
  'LC-08': { name: "Micoud", type: "District" },
  'LC-10': { name: "Soufrière", type: "District" },
  'LC-11': { name: "Vieux Fort", type: "District" },
  'LC-12': { name: "Canaries", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
