// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'LI';
export const countryName = "Liechtenstein";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'LI-01': { name: "Balzers", type: "Commune" },
  'LI-02': { name: "Eschen", type: "Commune" },
  'LI-03': { name: "Gamprin", type: "Commune" },
  'LI-04': { name: "Mauren", type: "Commune" },
  'LI-05': { name: "Planken", type: "Commune" },
  'LI-06': { name: "Ruggell", type: "Commune" },
  'LI-07': { name: "Schaan", type: "Commune" },
  'LI-08': { name: "Schellenberg", type: "Commune" },
  'LI-09': { name: "Triesen", type: "Commune" },
  'LI-10': { name: "Triesenberg", type: "Commune" },
  'LI-11': { name: "Vaduz", type: "Commune" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
