// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'LK';
export const countryName = "Sri Lanka";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'LK-1': { name: "Basnāhira paḷāta", type: "Province" },
  'LK-11': { name: "Colombo", type: "District" },
  'LK-12': { name: "Gampaha", type: "District" },
  'LK-13': { name: "Kalutara", type: "District" },
  'LK-2': { name: "Central Province", type: "Province" },
  'LK-21': { name: "Kandy", type: "District" },
  'LK-22': { name: "Matale", type: "District" },
  'LK-23': { name: "Nuvara Ĕliya", type: "District" },
  'LK-3': { name: "Dakuṇu paḷāta", type: "Province" },
  'LK-31': { name: "Gālla", type: "District" },
  'LK-32': { name: "Matara", type: "District" },
  'LK-33': { name: "Ampāntōṭṭai", type: "District" },
  'LK-4': { name: "Northern Province", type: "Province" },
  'LK-41': { name: "Jaffna", type: "District" },
  'LK-42': { name: "Kilinochchi", type: "District" },
  'LK-43': { name: "Mannar", type: "District" },
  'LK-44': { name: "Vavuniya", type: "District" },
  'LK-45': { name: "Mulativ", type: "District" },
  'LK-5': { name: "Eastern Province", type: "Province" },
  'LK-51': { name: "Batticaloa", type: "District" },
  'LK-52': { name: "Ampara", type: "District" },
  'LK-53': { name: "Tirukŏṇamalai", type: "District" },
  'LK-6': { name: "North Western Province", type: "Province" },
  'LK-61': { name: "Kuruṇægala", type: "District" },
  'LK-62': { name: "Puttalam", type: "District" },
  'LK-7': { name: "North Central Province", type: "Province" },
  'LK-71': { name: "Anuradhapura", type: "District" },
  'LK-72': { name: "Pŏlaṉṉaṛuvai", type: "District" },
  'LK-8': { name: "Ūvā mākāṇam", type: "Province" },
  'LK-81': { name: "Badulla", type: "District" },
  'LK-82': { name: "Monaragala", type: "District" },
  'LK-9': { name: "Chappirakamuva mākāṇam", type: "Province" },
  'LK-91': { name: "Irattiṉapuri", type: "District" },
  'LK-92': { name: "Kægalla", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
