// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'LR';
export const countryName = "Liberia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'LR-BG': { name: "Bong", type: "County" },
  'LR-BM': { name: "Bomi", type: "County" },
  'LR-CM': { name: "Grand Cape Mount", type: "County" },
  'LR-GB': { name: "Grand Bassa", type: "County" },
  'LR-GG': { name: "Grand Gedeh", type: "County" },
  'LR-GK': { name: "Grand Kru", type: "County" },
  'LR-GP': { name: "Gbarpolu", type: "County" },
  'LR-LO': { name: "Lofa", type: "County" },
  'LR-MG': { name: "Margibi", type: "County" },
  'LR-MO': { name: "Montserrado", type: "County" },
  'LR-MY': { name: "Maryland", type: "County" },
  'LR-NI': { name: "Nimba", type: "County" },
  'LR-RG': { name: "River Gee", type: "County" },
  'LR-RI': { name: "Rivercess", type: "County" },
  'LR-SI': { name: "Sinoe", type: "County" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
