// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'LS';
export const countryName = "Lesotho";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'LS-A': { name: "Maseru", type: "District" },
  'LS-B': { name: "Butha-Buthe", type: "District" },
  'LS-C': { name: "Leribe", type: "District" },
  'LS-D': { name: "Berea", type: "District" },
  'LS-E': { name: "Mafeteng", type: "District" },
  'LS-F': { name: "Mohale's Hoek", type: "District" },
  'LS-G': { name: "Quthing", type: "District" },
  'LS-H': { name: "Qacha's Nek", type: "District" },
  'LS-J': { name: "Mokhotlong", type: "District" },
  'LS-K': { name: "Thaba-Tseka", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
