// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'LU';
export const countryName = "Luxembourg";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'LU-D': { name: "Diekirch", type: "District" },
  'LU-G': { name: "Grevenmacher", type: "District" },
  'LU-L': { name: "Lëtzebuerg", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
