// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'LY';
export const countryName = "Libya";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'LY-BA': { name: "Banghāzī", type: "Popularate" },
  'LY-BU': { name: "Al Buţnān", type: "Popularate" },
  'LY-DR': { name: "Darnah", type: "Popularate" },
  'LY-GT': { name: "Ghāt", type: "Popularate" },
  'LY-JA': { name: "Al Jabal al Akhḑar", type: "Popularate" },
  'LY-JG': { name: "Al Jabal al Gharbī", type: "Popularate" },
  'LY-JI': { name: "Al Jifārah", type: "Popularate" },
  'LY-JU': { name: "Al Jufrah", type: "Popularate" },
  'LY-KF': { name: "Al Kufrah", type: "Popularate" },
  'LY-MB': { name: "Al Marqab", type: "Popularate" },
  'LY-MI': { name: "Mişrātah", type: "Popularate" },
  'LY-MJ': { name: "Al Marj", type: "Popularate" },
  'LY-MQ': { name: "Murzuq", type: "Popularate" },
  'LY-NL': { name: "Nālūt", type: "Popularate" },
  'LY-NQ': { name: "An Nuqāţ al Khams", type: "Popularate" },
  'LY-SB': { name: "Sabhā", type: "Popularate" },
  'LY-SR': { name: "Surt", type: "Popularate" },
  'LY-TB': { name: "Ţarābulus", type: "Popularate" },
  'LY-WA': { name: "Al Wāḩāt", type: "Popularate" },
  'LY-WD': { name: "Wādī al Ḩayāt", type: "Popularate" },
  'LY-WS': { name: "Wādī ash Shāţi’", type: "Popularate" },
  'LY-ZA': { name: "Az Zāwiyah", type: "Popularate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
