// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MC';
export const countryName = "Monaco";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MC-CL': { name: "La Colle", type: "Quarter" },
  'MC-CO': { name: "La Condamine", type: "Quarter" },
  'MC-FO': { name: "Fontvieille", type: "Quarter" },
  'MC-GA': { name: "La Gare", type: "Quarter" },
  'MC-JE': { name: "Jardin Exotique", type: "Quarter" },
  'MC-LA': { name: "Larvotto", type: "Quarter" },
  'MC-MA': { name: "Malbousquet", type: "Quarter" },
  'MC-MC': { name: "Monte-Carlo", type: "Quarter" },
  'MC-MG': { name: "Moneghetti", type: "Quarter" },
  'MC-MO': { name: "Monaco-Ville", type: "Quarter" },
  'MC-MU': { name: "Moulins", type: "Quarter" },
  'MC-PH': { name: "Port-Hercule", type: "Quarter" },
  'MC-SD': { name: "Sainte-Dévote", type: "Quarter" },
  'MC-SO': { name: "La Source", type: "Quarter" },
  'MC-SP': { name: "Spélugues", type: "Quarter" },
  'MC-SR': { name: "Saint-Roman", type: "Quarter" },
  'MC-VR': { name: "Vallon de la Rousse", type: "Quarter" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
