// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MD';
export const countryName = "Moldova";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MD-AN': { name: "Anenii Noi", type: "District" },
  'MD-BA': { name: "Bălţi", type: "City" },
  'MD-BD': { name: "Bender", type: "City" },
  'MD-BR': { name: "Briceni", type: "District" },
  'MD-BS': { name: "Basarabeasca", type: "District" },
  'MD-CA': { name: "Cahul", type: "District" },
  'MD-CL': { name: "Călăraşi", type: "District" },
  'MD-CM': { name: "Cimişlia", type: "District" },
  'MD-CR': { name: "Criuleni", type: "District" },
  'MD-CS': { name: "Căuşeni", type: "District" },
  'MD-CT': { name: "Cantemir", type: "District" },
  'MD-CU': { name: "Chişinău", type: "City" },
  'MD-DO': { name: "Donduşeni", type: "District" },
  'MD-DR': { name: "Drochia", type: "District" },
  'MD-DU': { name: "Dubăsari", type: "District" },
  'MD-ED': { name: "Edineţ", type: "District" },
  'MD-FA': { name: "Făleşti", type: "District" },
  'MD-FL': { name: "Floreşti", type: "District" },
  'MD-GA': { name: "Găgăuzia, Unitatea teritorială autonomă", type: "Autonomous territorial unit" },
  'MD-GL': { name: "Glodeni", type: "District" },
  'MD-HI': { name: "Hînceşti", type: "District" },
  'MD-IA': { name: "Ialoveni", type: "District" },
  'MD-LE': { name: "Leova", type: "District" },
  'MD-NI': { name: "Nisporeni", type: "District" },
  'MD-OC': { name: "Ocniţa", type: "District" },
  'MD-OR': { name: "Orhei", type: "District" },
  'MD-RE': { name: "Rezina", type: "District" },
  'MD-RI': { name: "Rîşcani", type: "District" },
  'MD-SD': { name: "Şoldăneşti", type: "District" },
  'MD-SI': { name: "Sîngerei", type: "District" },
  'MD-SN': { name: "Stînga Nistrului, unitatea teritorială din", type: "Territorial unit" },
  'MD-SO': { name: "Soroca", type: "District" },
  'MD-ST': { name: "Străşeni", type: "District" },
  'MD-SV': { name: "Ştefan Vodă", type: "District" },
  'MD-TA': { name: "Taraclia", type: "District" },
  'MD-TE': { name: "Teleneşti", type: "District" },
  'MD-UN': { name: "Ungheni", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
