// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'ME';
export const countryName = "Montenegro";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'ME-01': { name: "Andrijevica", type: "Municipality" },
  'ME-02': { name: "Bar", type: "Municipality" },
  'ME-03': { name: "Berane", type: "Municipality" },
  'ME-04': { name: "Bijelo Polje", type: "Municipality" },
  'ME-05': { name: "Budva", type: "Municipality" },
  'ME-06': { name: "Cetinje", type: "Municipality" },
  'ME-07': { name: "Danilovgrad", type: "Municipality" },
  'ME-08': { name: "Herceg-Novi", type: "Municipality" },
  'ME-09': { name: "Kolašin", type: "Municipality" },
  'ME-10': { name: "Kotor", type: "Municipality" },
  'ME-11': { name: "Mojkovac", type: "Municipality" },
  'ME-12': { name: "Nikšić", type: "Municipality" },
  'ME-13': { name: "Plav", type: "Municipality" },
  'ME-14': { name: "Pljevlja", type: "Municipality" },
  'ME-15': { name: "Plužine", type: "Municipality" },
  'ME-16': { name: "Podgorica", type: "Municipality" },
  'ME-17': { name: "Rožaje", type: "Municipality" },
  'ME-18': { name: "Šavnik", type: "Municipality" },
  'ME-19': { name: "Tivat", type: "Municipality" },
  'ME-20': { name: "Ulcinj", type: "Municipality" },
  'ME-21': { name: "Žabljak", type: "Municipality" },
  'ME-22': { name: "Gusinje", type: "Municipality" },
  'ME-23': { name: "Petnjica", type: "Municipality" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
