// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MF';
export const countryName = "St. Martin";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MF-MF': { name: "St. Martin", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
