// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MG';
export const countryName = "Madagascar";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MG-A': { name: "Toamasina", type: "Province" },
  'MG-D': { name: "Antsiranana", type: "Province" },
  'MG-F': { name: "Fianarantsoa", type: "Province" },
  'MG-M': { name: "Mahajanga", type: "Province" },
  'MG-T': { name: "Antananarivo", type: "Province" },
  'MG-U': { name: "Toliara", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
