// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MH';
export const countryName = "Marshall Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MH-ALK': { name: "Ailuk", type: "Municipality" },
  'MH-ALL': { name: "Ailinglaplap", type: "Municipality" },
  'MH-ARN': { name: "Arno", type: "Municipality" },
  'MH-AUR': { name: "Aur", type: "Municipality" },
  'MH-EBO': { name: "Ebon", type: "Municipality" },
  'MH-ENI': { name: "Enewetak and Ujelang", type: "Municipality" },
  'MH-JAB': { name: "Jabat", type: "Municipality" },
  'MH-JAL': { name: "Jaluit", type: "Municipality" },
  'MH-KIL': { name: "Bikini and Kili", type: "Municipality" },
  'MH-KWA': { name: "Kwajalein", type: "Municipality" },
  'MH-L': { name: "Ralik chain", type: "Chain" },
  'MH-LAE': { name: "Lae", type: "Municipality" },
  'MH-LIB': { name: "Lib", type: "Municipality" },
  'MH-LIK': { name: "Likiep", type: "Municipality" },
  'MH-MAJ': { name: "Majuro", type: "Municipality" },
  'MH-MAL': { name: "Maloelap", type: "Municipality" },
  'MH-MEJ': { name: "Mejit", type: "Municipality" },
  'MH-MIL': { name: "Mili", type: "Municipality" },
  'MH-NMK': { name: "Namdrik", type: "Municipality" },
  'MH-NMU': { name: "Namu", type: "Municipality" },
  'MH-RON': { name: "Rongelap", type: "Municipality" },
  'MH-T': { name: "Ratak chain", type: "Chain" },
  'MH-UJA': { name: "Ujae", type: "Municipality" },
  'MH-UTI': { name: "Utrik", type: "Municipality" },
  'MH-WTH': { name: "Wotho", type: "Municipality" },
  'MH-WTJ': { name: "Wotje", type: "Municipality" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
