// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'ML';
export const countryName = "Mali";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'ML-1': { name: "Kayes", type: "Region" },
  'ML-2': { name: "Koulikoro", type: "Region" },
  'ML-3': { name: "Sikasso", type: "Region" },
  'ML-4': { name: "Ségou", type: "Region" },
  'ML-5': { name: "Mopti", type: "Region" },
  'ML-6': { name: "Tombouctou", type: "Region" },
  'ML-7': { name: "Gao", type: "Region" },
  'ML-8': { name: "Kidal", type: "Region" },
  'ML-BKO': { name: "Bamako", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
