// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MM';
export const countryName = "Myanmar";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MM-01': { name: "Sagaing", type: "Region" },
  'MM-02': { name: "Bago", type: "Region" },
  'MM-03': { name: "Magway", type: "Region" },
  'MM-04': { name: "Mandalay", type: "Region" },
  'MM-05': { name: "Taninthayi", type: "Region" },
  'MM-06': { name: "Yangon", type: "Region" },
  'MM-07': { name: "Ayeyawady", type: "Region" },
  'MM-11': { name: "Kachin", type: "State" },
  'MM-12': { name: "Kayah", type: "State" },
  'MM-13': { name: "Kayin", type: "State" },
  'MM-14': { name: "Chin", type: "State" },
  'MM-15': { name: "Mon", type: "State" },
  'MM-16': { name: "Rakhine", type: "State" },
  'MM-17': { name: "Shan", type: "State" },
  'MM-18': { name: "Nay Pyi Taw", type: "Union territory" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
