// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MN';
export const countryName = "Mongolia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MN-035': { name: "Orhon", type: "Province" },
  'MN-037': { name: "Darhan uul", type: "Province" },
  'MN-039': { name: "Hentiy", type: "Province" },
  'MN-041': { name: "Hövsgöl", type: "Province" },
  'MN-043': { name: "Hovd", type: "Province" },
  'MN-046': { name: "Uvs", type: "Province" },
  'MN-047': { name: "Töv", type: "Province" },
  'MN-049': { name: "Selenge", type: "Province" },
  'MN-051': { name: "Sühbaatar", type: "Province" },
  'MN-053': { name: "Ömnögovĭ", type: "Province" },
  'MN-055': { name: "Övörhangay", type: "Province" },
  'MN-057': { name: "Dzavhan", type: "Province" },
  'MN-059': { name: "Dundgovĭ", type: "Province" },
  'MN-061': { name: "Dornod", type: "Province" },
  'MN-063': { name: "Dornogovĭ", type: "Province" },
  'MN-064': { name: "Govĭ-Sümber", type: "Province" },
  'MN-065': { name: "Govĭ-Altay", type: "Province" },
  'MN-067': { name: "Bulgan", type: "Province" },
  'MN-069': { name: "Bayanhongor", type: "Province" },
  'MN-071': { name: "Bayan-Ölgiy", type: "Province" },
  'MN-073': { name: "Arhangay", type: "Province" },
  'MN-1': { name: "Ulaanbaatar", type: "Capital city" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
