// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MO';
export const countryName = "Macau";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MO-MO': { name: "Macau", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
