// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MP';
export const countryName = "Northern Mariana Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MP-MP': { name: "Northern Mariana Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
