// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MQ';
export const countryName = "Martinique";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MQ-MQ': { name: "Martinique", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
