// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MR';
export const countryName = "Mauritania";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MR-01': { name: "Hodh ech Chargui", type: "Region" },
  'MR-02': { name: "Hodh el Gharbi", type: "Region" },
  'MR-03': { name: "Assaba", type: "Region" },
  'MR-04': { name: "Gorgol", type: "Region" },
  'MR-05': { name: "Brakna", type: "Region" },
  'MR-06': { name: "Trarza", type: "Region" },
  'MR-07': { name: "Adrar", type: "Region" },
  'MR-08': { name: "Dakhlet Nouâdhibou", type: "Region" },
  'MR-09': { name: "Tagant", type: "Region" },
  'MR-10': { name: "Guidimaka", type: "Region" },
  'MR-11': { name: "Tiris Zemmour", type: "Region" },
  'MR-12': { name: "Inchiri", type: "Region" },
  'MR-NKC': { name: "Nouakchott", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
