// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MS';
export const countryName = "Montserrat";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MS-MS': { name: "Montserrat", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
