// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MU';
export const countryName = "Mauritius";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MU-AG': { name: "Agalega Islands", type: "Dependency" },
  'MU-BL': { name: "Black River", type: "District" },
  'MU-BR': { name: "Beau Bassin-Rose Hill", type: "City" },
  'MU-CC': { name: "Cargados Carajos Shoals", type: "Dependency" },
  'MU-CU': { name: "Curepipe", type: "City" },
  'MU-FL': { name: "Flacq", type: "District" },
  'MU-GP': { name: "Grand Port", type: "District" },
  'MU-MO': { name: "Moka", type: "District" },
  'MU-PA': { name: "Pamplemousses", type: "District" },
  'MU-PL': { name: "Port Louis", type: "District" },
  'MU-PU': { name: "Port Louis", type: "City" },
  'MU-PW': { name: "Plaines Wilhems", type: "District" },
  'MU-QB': { name: "Quatre Bornes", type: "City" },
  'MU-RO': { name: "Rodrigues Island", type: "Dependency" },
  'MU-RR': { name: "Rivière du Rempart", type: "District" },
  'MU-SA': { name: "Savanne", type: "District" },
  'MU-VP': { name: "Vacoas-Phoenix", type: "City" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
