// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MV';
export const countryName = "Maldives";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MV-00': { name: "Alifu Dhaalu", type: "Administrative atoll" },
  'MV-01': { name: "Addu Atholhu", type: "Administrative atoll" },
  'MV-02': { name: "Alifu Alifu", type: "Administrative atoll" },
  'MV-03': { name: "Faadhippolhu", type: "Administrative atoll" },
  'MV-04': { name: "Felidhu Atholhu", type: "Administrative atoll" },
  'MV-05': { name: "Hadhdhunmathi", type: "Administrative atoll" },
  'MV-07': { name: "Haa Alifu", type: "Administrative atoll" },
  'MV-08': { name: "Kolhumadulu", type: "Administrative atoll" },
  'MV-12': { name: "Meemu", type: "Administrative atoll" },
  'MV-13': { name: "Maalhosmadulu Uthuruburi", type: "Administrative atoll" },
  'MV-14': { name: "Faafu", type: "Administrative atoll" },
  'MV-17': { name: "Dhaalu", type: "Administrative atoll" },
  'MV-20': { name: "Baa", type: "Administrative atoll" },
  'MV-23': { name: "Haa Dhaalu", type: "Administrative atoll" },
  'MV-24': { name: "Miladhunmadulu Uthuruburi", type: "Administrative atoll" },
  'MV-25': { name: "Miladhunmadulu Dhekunuburi", type: "Administrative atoll" },
  'MV-26': { name: "Kaafu", type: "Administrative atoll" },
  'MV-27': { name: "Gaafu Alifu", type: "Administrative atoll" },
  'MV-28': { name: "Gaafu Dhaalu", type: "Administrative atoll" },
  'MV-29': { name: "Fuvammulah", type: "Administrative atoll" },
  'MV-CE': { name: "Central", type: "Province" },
  'MV-MLE': { name: "Maale", type: "Capital" },
  'MV-NC': { name: "Medhu-Uthuru", type: "Province" },
  'MV-NO': { name: "North", type: "Province" },
  'MV-SC': { name: "Medhu-Dhekunu", type: "Province" },
  'MV-SU': { name: "Dhekunu", type: "Province" },
  'MV-UN': { name: "Mathi-Uthuru", type: "Province" },
  'MV-US': { name: "Mathi-Dhekunu", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
