// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MW';
export const countryName = "Malawi";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MW-BA': { name: "Balaka", type: "District" },
  'MW-BL': { name: "Blantyre", type: "District" },
  'MW-C': { name: "Central Region", type: "Region" },
  'MW-CK': { name: "Chikwawa", type: "District" },
  'MW-CR': { name: "Chiradzulu", type: "District" },
  'MW-CT': { name: "Chitipa", type: "District" },
  'MW-DE': { name: "Dedza", type: "District" },
  'MW-DO': { name: "Dowa", type: "District" },
  'MW-KR': { name: "Karonga", type: "District" },
  'MW-KS': { name: "Kasungu", type: "District" },
  'MW-LI': { name: "Lilongwe", type: "District" },
  'MW-LK': { name: "Likoma", type: "District" },
  'MW-MC': { name: "Mchinji", type: "District" },
  'MW-MG': { name: "Mangochi", type: "District" },
  'MW-MH': { name: "Machinga", type: "District" },
  'MW-MU': { name: "Mulanje", type: "District" },
  'MW-MW': { name: "Mwanza", type: "District" },
  'MW-MZ': { name: "Mzimba", type: "District" },
  'MW-N': { name: "Chakumpoto", type: "Region" },
  'MW-NB': { name: "Nkhata Bay", type: "District" },
  'MW-NE': { name: "Neno", type: "District" },
  'MW-NI': { name: "Ntchisi", type: "District" },
  'MW-NK': { name: "Nkhotakota", type: "District" },
  'MW-NS': { name: "Nsanje", type: "District" },
  'MW-NU': { name: "Ntcheu", type: "District" },
  'MW-PH': { name: "Phalombe", type: "District" },
  'MW-RU': { name: "Rumphi", type: "District" },
  'MW-S': { name: "Chakumwera", type: "Region" },
  'MW-SA': { name: "Salima", type: "District" },
  'MW-TH': { name: "Thyolo", type: "District" },
  'MW-ZO': { name: "Zomba", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
