// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MX';
export const countryName = "Mexico";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MX-AGU': { name: "Aguascalientes", type: "State" },
  'MX-BCN': { name: "Baja California", type: "State" },
  'MX-BCS': { name: "Baja California Sur", type: "State" },
  'MX-CAM': { name: "Campeche", type: "State" },
  'MX-CHH': { name: "Chihuahua", type: "State" },
  'MX-CHP': { name: "Chiapas", type: "State" },
  'MX-CMX': { name: "Ciudad de México", type: "Federal District" },
  'MX-COA': { name: "Coahuila de Zaragoza", type: "State" },
  'MX-COL': { name: "Colima", type: "State" },
  'MX-DUR': { name: "Durango", type: "State" },
  'MX-GRO': { name: "Guerrero", type: "State" },
  'MX-GUA': { name: "Guanajuato", type: "State" },
  'MX-HID': { name: "Hidalgo", type: "State" },
  'MX-JAL': { name: "Jalisco", type: "State" },
  'MX-MEX': { name: "México", type: "State" },
  'MX-MIC': { name: "Michoacán de Ocampo", type: "State" },
  'MX-MOR': { name: "Morelos", type: "State" },
  'MX-NAY': { name: "Nayarit", type: "State" },
  'MX-NLE': { name: "Nuevo León", type: "State" },
  'MX-OAX': { name: "Oaxaca", type: "State" },
  'MX-PUE': { name: "Puebla", type: "State" },
  'MX-QUE': { name: "Querétaro", type: "State" },
  'MX-ROO': { name: "Quintana Roo", type: "State" },
  'MX-SIN': { name: "Sinaloa", type: "State" },
  'MX-SLP': { name: "San Luis Potosí", type: "State" },
  'MX-SON': { name: "Sonora", type: "State" },
  'MX-TAB': { name: "Tabasco", type: "State" },
  'MX-TAM': { name: "Tamaulipas", type: "State" },
  'MX-TLA': { name: "Tlaxcala", type: "State" },
  'MX-VER': { name: "Veracruz de Ignacio de la Llave", type: "State" },
  'MX-YUC': { name: "Yucatán", type: "State" },
  'MX-ZAC': { name: "Zacatecas", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
