// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MY';
export const countryName = "Malaysia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MY-01': { name: "Johor", type: "State" },
  'MY-02': { name: "Kedah", type: "State" },
  'MY-03': { name: "Kelantan", type: "State" },
  'MY-04': { name: "Melaka", type: "State" },
  'MY-05': { name: "Negeri Sembilan", type: "State" },
  'MY-06': { name: "Pahang", type: "State" },
  'MY-07': { name: "Pulau Pinang", type: "State" },
  'MY-08': { name: "Perak", type: "State" },
  'MY-09': { name: "Perlis", type: "State" },
  'MY-10': { name: "Selangor", type: "State" },
  'MY-11': { name: "Terengganu", type: "State" },
  'MY-12': { name: "Sabah", type: "State" },
  'MY-13': { name: "Sarawak", type: "State" },
  'MY-14': { name: "Wilayah Persekutuan Kuala Lumpur", type: "Federal territory" },
  'MY-15': { name: "Wilayah Persekutuan Labuan", type: "Federal territory" },
  'MY-16': { name: "Wilayah Persekutuan Putrajaya", type: "Federal territory" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
