// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'MZ';
export const countryName = "Mozambique";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'MZ-A': { name: "Niassa", type: "Province" },
  'MZ-B': { name: "Manica", type: "Province" },
  'MZ-G': { name: "Gaza", type: "Province" },
  'MZ-I': { name: "Inhambane", type: "Province" },
  'MZ-L': { name: "Maputo", type: "Province" },
  'MZ-MPM': { name: "Maputo", type: "City" },
  'MZ-N': { name: "Nampula", type: "Province" },
  'MZ-P': { name: "Cabo Delgado", type: "Province" },
  'MZ-Q': { name: "Zambézia", type: "Province" },
  'MZ-S': { name: "Sofala", type: "Province" },
  'MZ-T': { name: "Tete", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
