// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NA';
export const countryName = "Namibia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NA-CA': { name: "Zambezi", type: "Region" },
  'NA-ER': { name: "Erongo", type: "Region" },
  'NA-HA': { name: "Hardap", type: "Region" },
  'NA-KA': { name: "Karas", type: "Region" },
  'NA-KE': { name: "Kavango East", type: "Region" },
  'NA-KH': { name: "Khomas", type: "Region" },
  'NA-KU': { name: "Kunene", type: "Region" },
  'NA-KW': { name: "Kavango West", type: "Region" },
  'NA-OD': { name: "Otjozondjupa", type: "Region" },
  'NA-OH': { name: "Omaheke", type: "Region" },
  'NA-ON': { name: "Oshana", type: "Region" },
  'NA-OS': { name: "Omusati", type: "Region" },
  'NA-OT': { name: "Oshikoto", type: "Region" },
  'NA-OW': { name: "Ohangwena", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
