// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NC';
export const countryName = "New Caledonia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NC-NC': { name: "New Caledonia", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
