// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NE';
export const countryName = "Niger";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NE-1': { name: "Agadez", type: "Region" },
  'NE-2': { name: "Diffa", type: "Region" },
  'NE-3': { name: "Dosso", type: "Region" },
  'NE-4': { name: "Maradi", type: "Region" },
  'NE-5': { name: "Tahoua", type: "Region" },
  'NE-6': { name: "Tillabéri", type: "Region" },
  'NE-7': { name: "Zinder", type: "Region" },
  'NE-8': { name: "Niamey", type: "Urban community" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
