// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NF';
export const countryName = "Norfolk Island";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NF-NF': { name: "Norfolk Island", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
