// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NG';
export const countryName = "Nigeria";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NG-AB': { name: "Abia", type: "State" },
  'NG-AD': { name: "Adamawa", type: "State" },
  'NG-AK': { name: "Akwa Ibom", type: "State" },
  'NG-AN': { name: "Anambra", type: "State" },
  'NG-BA': { name: "Bauchi", type: "State" },
  'NG-BE': { name: "Benue", type: "State" },
  'NG-BO': { name: "Borno", type: "State" },
  'NG-BY': { name: "Bayelsa", type: "State" },
  'NG-CR': { name: "Cross River", type: "State" },
  'NG-DE': { name: "Delta", type: "State" },
  'NG-EB': { name: "Ebonyi", type: "State" },
  'NG-ED': { name: "Edo", type: "State" },
  'NG-EK': { name: "Ekiti", type: "State" },
  'NG-EN': { name: "Enugu", type: "State" },
  'NG-FC': { name: "Abuja Federal Capital Territory", type: "Capital territory" },
  'NG-GO': { name: "Gombe", type: "State" },
  'NG-IM': { name: "Imo", type: "State" },
  'NG-JI': { name: "Jigawa", type: "State" },
  'NG-KD': { name: "Kaduna", type: "State" },
  'NG-KE': { name: "Kebbi", type: "State" },
  'NG-KN': { name: "Kano", type: "State" },
  'NG-KO': { name: "Kogi", type: "State" },
  'NG-KT': { name: "Katsina", type: "State" },
  'NG-KW': { name: "Kwara", type: "State" },
  'NG-LA': { name: "Lagos", type: "State" },
  'NG-NA': { name: "Nasarawa", type: "State" },
  'NG-NI': { name: "Niger", type: "State" },
  'NG-OG': { name: "Ogun", type: "State" },
  'NG-ON': { name: "Ondo", type: "State" },
  'NG-OS': { name: "Osun", type: "State" },
  'NG-OY': { name: "Oyo", type: "State" },
  'NG-PL': { name: "Plateau", type: "State" },
  'NG-RI': { name: "Rivers", type: "State" },
  'NG-SO': { name: "Sokoto", type: "State" },
  'NG-TA': { name: "Taraba", type: "State" },
  'NG-YO': { name: "Yobe", type: "State" },
  'NG-ZA': { name: "Zamfara", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
