// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NI';
export const countryName = "Nicaragua";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NI-AN': { name: "Atlántico Norte", type: "Autonomous region" },
  'NI-AS': { name: "Atlántico Sur", type: "Autonomous region" },
  'NI-BO': { name: "Boaco", type: "Department" },
  'NI-CA': { name: "Carazo", type: "Department" },
  'NI-CI': { name: "Chinandega", type: "Department" },
  'NI-CO': { name: "Chontales", type: "Department" },
  'NI-ES': { name: "Estelí", type: "Department" },
  'NI-GR': { name: "Granada", type: "Department" },
  'NI-JI': { name: "Jinotega", type: "Department" },
  'NI-LE': { name: "León", type: "Department" },
  'NI-MD': { name: "Madriz", type: "Department" },
  'NI-MN': { name: "Managua", type: "Department" },
  'NI-MS': { name: "Masaya", type: "Department" },
  'NI-MT': { name: "Matagalpa", type: "Department" },
  'NI-NS': { name: "Nueva Segovia", type: "Department" },
  'NI-RI': { name: "Rivas", type: "Department" },
  'NI-SJ': { name: "Río San Juan", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
