// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NL';
export const countryName = "Netherlands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NL-AW': { name: "Aruba", type: "Country" },
  'NL-BQ1': { name: "Bonaire", type: "Special municipality" },
  'NL-BQ2': { name: "Saba", type: "Special municipality" },
  'NL-BQ3': { name: "Sint Eustatius", type: "Special municipality" },
  'NL-CW': { name: "Curaçao", type: "Country" },
  'NL-DR': { name: "Drenthe", type: "Province" },
  'NL-FL': { name: "Flevoland", type: "Province" },
  'NL-FR': { name: "Fryslân", type: "Province" },
  'NL-GE': { name: "Gelderland", type: "Province" },
  'NL-GR': { name: "Groningen", type: "Province" },
  'NL-LI': { name: "Limburg", type: "Province" },
  'NL-NB': { name: "Noord-Brabant", type: "Province" },
  'NL-NH': { name: "Noord-Holland", type: "Province" },
  'NL-OV': { name: "Overijssel", type: "Province" },
  'NL-SX': { name: "Sint Maarten", type: "Country" },
  'NL-UT': { name: "Utrecht", type: "Province" },
  'NL-ZE': { name: "Zeeland", type: "Province" },
  'NL-ZH': { name: "Zuid-Holland", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
