// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NO';
export const countryName = "Norway";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NO-01': { name: "Østfold", type: "County" },
  'NO-02': { name: "Akershus", type: "County" },
  'NO-03': { name: "Oslo", type: "County" },
  'NO-04': { name: "Hedmark", type: "County" },
  'NO-05': { name: "Oppland", type: "County" },
  'NO-06': { name: "Buskerud", type: "County" },
  'NO-07': { name: "Vestfold", type: "County" },
  'NO-08': { name: "Telemark", type: "County" },
  'NO-09': { name: "Aust-Agder", type: "County" },
  'NO-10': { name: "Vest-Agder", type: "County" },
  'NO-11': { name: "Rogaland", type: "County" },
  'NO-12': { name: "Hordaland", type: "County" },
  'NO-14': { name: "Sogn og Fjordane", type: "County" },
  'NO-15': { name: "Møre og Romsdal", type: "County" },
  'NO-16': { name: "Sør-Trøndelag", type: "County" },
  'NO-17': { name: "Nord-Trøndelag", type: "County" },
  'NO-18': { name: "Nordland", type: "County" },
  'NO-19': { name: "Romsa", type: "County" },
  'NO-20': { name: "Finnmark", type: "County" },
  'NO-21': { name: "Svalbard", type: "Arctic region" },
  'NO-22': { name: "Jan Mayen", type: "Arctic region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
