// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NP';
export const countryName = "Nepal";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NP-P1': { name: "Koshi", type: "Province" },
  'NP-P2': { name: "Madhesh", type: "Province" },
  'NP-P3': { name: "Bagmati", type: "Province" },
  'NP-P4': { name: "Gandaki", type: "Province" },
  'NP-P5': { name: "Lumbini", type: "Province" },
  'NP-P6': { name: "Karnali", type: "Province" },
  'NP-P7': { name: "Sudurpashchim", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
