// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NR';
export const countryName = "Nauru";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NR-01': { name: "Aiwo", type: "District" },
  'NR-02': { name: "Anabar", type: "District" },
  'NR-03': { name: "Anetan", type: "District" },
  'NR-04': { name: "Anibare", type: "District" },
  'NR-05': { name: "Baiti", type: "District" },
  'NR-06': { name: "Boe", type: "District" },
  'NR-07': { name: "Buada", type: "District" },
  'NR-08': { name: "Denigomodu", type: "District" },
  'NR-09': { name: "Ewa", type: "District" },
  'NR-10': { name: "Ijuw", type: "District" },
  'NR-11': { name: "Meneng", type: "District" },
  'NR-12': { name: "Nibok", type: "District" },
  'NR-13': { name: "Uaboe", type: "District" },
  'NR-14': { name: "Yaren", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
