// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NU';
export const countryName = "Niue";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NU-NU': { name: "Niue", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
