// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'NZ';
export const countryName = "New Zealand";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'NZ-AUK': { name: "Auckland", type: "Unitary authority" },
  'NZ-BOP': { name: "Bay of Plenty", type: "Regional council" },
  'NZ-CAN': { name: "Canterbury", type: "Regional council" },
  'NZ-CIT': { name: "Chatham Islands Territory", type: "Special island authority" },
  'NZ-GIS': { name: "Gisborne District", type: "Unitary authority" },
  'NZ-HKB': { name: "Hawke's Bay", type: "Regional council" },
  'NZ-MBH': { name: "Marlborough District", type: "Unitary authority" },
  'NZ-MWT': { name: "Manawatu-Wanganui", type: "Regional council" },
  'NZ-N': { name: "North Island", type: "Island" },
  'NZ-NSN': { name: "Nelson City", type: "Unitary authority" },
  'NZ-NTL': { name: "Northland", type: "Regional council" },
  'NZ-OTA': { name: "Otago", type: "Regional council" },
  'NZ-S': { name: "South Island", type: "Island" },
  'NZ-STL': { name: "Southland", type: "Regional council" },
  'NZ-TAS': { name: "Tasman District", type: "Unitary authority" },
  'NZ-TKI': { name: "Taranaki", type: "Regional council" },
  'NZ-WGN': { name: "Wellington", type: "Regional council" },
  'NZ-WKO': { name: "Waikato", type: "Regional council" },
  'NZ-WTC': { name: "West Coast", type: "Regional council" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
