// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'OM';
export const countryName = "Oman";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'OM-BA': { name: "Al Bāţinah", type: "Region" },
  'OM-BU': { name: "Al Buraymī", type: "Governorate" },
  'OM-DA': { name: "Ad Dākhilīyah", type: "Region" },
  'OM-MA': { name: "Masqaţ", type: "Governorate" },
  'OM-MU': { name: "Musandam", type: "Governorate" },
  'OM-SH': { name: "Ash Sharqīyah", type: "Region" },
  'OM-WU': { name: "Al Wusţá", type: "Region" },
  'OM-ZA': { name: "Az̧ Z̧āhirah", type: "Region" },
  'OM-ZU': { name: "Z̧ufār", type: "Governorate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
