// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PA';
export const countryName = "Panama";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PA-1': { name: "Bocas del Toro", type: "Province" },
  'PA-10': { name: "Panamá Oeste", type: "Province" },
  'PA-2': { name: "Coclé", type: "Province" },
  'PA-3': { name: "Colón", type: "Province" },
  'PA-4': { name: "Chiriquí", type: "Province" },
  'PA-5': { name: "Darién", type: "Province" },
  'PA-6': { name: "Herrera", type: "Province" },
  'PA-7': { name: "Los Santos", type: "Province" },
  'PA-8': { name: "Panamá", type: "Province" },
  'PA-9': { name: "Veraguas", type: "Province" },
  'PA-EM': { name: "Emberá", type: "Indigenous region" },
  'PA-KY': { name: "Kuna Yala", type: "Indigenous region" },
  'PA-NB': { name: "Ngöbe-Buglé", type: "Indigenous region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
