// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PE';
export const countryName = "Peru";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PE-AMA': { name: "Amarumayu", type: "Region" },
  'PE-ANC': { name: "Ancash", type: "Region" },
  'PE-APU': { name: "Apurímac", type: "Region" },
  'PE-ARE': { name: "Arequipa", type: "Region" },
  'PE-AYA': { name: "Ayacucho", type: "Region" },
  'PE-CAJ': { name: "Cajamarca", type: "Region" },
  'PE-CAL': { name: "El Callao", type: "Region" },
  'PE-CUS': { name: "Cusco", type: "Region" },
  'PE-HUC': { name: "Huánuco", type: "Region" },
  'PE-HUV': { name: "Huancavelica", type: "Region" },
  'PE-ICA': { name: "Ica", type: "Region" },
  'PE-JUN': { name: "Hunin", type: "Region" },
  'PE-LAL': { name: "La Libertad", type: "Region" },
  'PE-LAM': { name: "Lambayeque", type: "Region" },
  'PE-LIM': { name: "Lima", type: "Region" },
  'PE-LMA': { name: "Lima hatun llaqta", type: "Municipality" },
  'PE-LOR': { name: "Loreto", type: "Region" },
  'PE-MDD': { name: "Madre de Dios", type: "Region" },
  'PE-MOQ': { name: "Moquegua", type: "Region" },
  'PE-PAS': { name: "Pasco", type: "Region" },
  'PE-PIU': { name: "Piura", type: "Region" },
  'PE-PUN': { name: "Puno", type: "Region" },
  'PE-SAM': { name: "San Martin", type: "Region" },
  'PE-TAC': { name: "Tacna", type: "Region" },
  'PE-TUM': { name: "Tumbes", type: "Region" },
  'PE-UCA': { name: "Ucayali", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
