// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PF';
export const countryName = "French Polynesia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PF-PF': { name: "French Polynesia", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
