// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PG';
export const countryName = "Papua New Guinea";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PG-CPK': { name: "Chimbu", type: "Province" },
  'PG-CPM': { name: "Central", type: "Province" },
  'PG-EBR': { name: "East New Britain", type: "Province" },
  'PG-EHG': { name: "Eastern Highlands", type: "Province" },
  'PG-EPW': { name: "Enga", type: "Province" },
  'PG-ESW': { name: "East Sepik", type: "Province" },
  'PG-GPK': { name: "Gulf", type: "Province" },
  'PG-HLA': { name: "Hela", type: "Province" },
  'PG-JWK': { name: "Jiwaka", type: "Province" },
  'PG-MBA': { name: "Milne Bay", type: "Province" },
  'PG-MPL': { name: "Morobe", type: "Province" },
  'PG-MPM': { name: "Madang", type: "Province" },
  'PG-MRL': { name: "Manus", type: "Province" },
  'PG-NCD': { name: "National Capital District", type: "District" },
  'PG-NIK': { name: "New Ireland", type: "Province" },
  'PG-NPP': { name: "Northern", type: "Province" },
  'PG-NSB': { name: "Bougainville", type: "Autonomous region" },
  'PG-SAN': { name: "West Sepik", type: "Province" },
  'PG-SHM': { name: "Southern Highlands", type: "Province" },
  'PG-WBK': { name: "West New Britain", type: "Province" },
  'PG-WHM': { name: "Western Highlands", type: "Province" },
  'PG-WPD': { name: "Western", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
