// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PK';
export const countryName = "Pakistan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PK-BA': { name: "Balochistan", type: "Province" },
  'PK-GB': { name: "Gilgit-Baltistān", type: "Pakistan administered area" },
  'PK-IS': { name: "Islāmābād", type: "Federal capital territory" },
  'PK-JK': { name: "Azad Kashmir", type: "Pakistan administered area" },
  'PK-KP': { name: "Khaībar Pakhtūnkhwā", type: "Province" },
  'PK-PB': { name: "Panjāb", type: "Province" },
  'PK-SD': { name: "Sindh", type: "Province" },
  'PK-TA': { name: "Federally Administered Tribal Areas", type: "Territory" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
