// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PL';
export const countryName = "Poland";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PL-DS': { name: "Dolnośląskie", type: "Province" },
  'PL-KP': { name: "Kujawsko-pomorskie", type: "Province" },
  'PL-LB': { name: "Lubuskie", type: "Province" },
  'PL-LD': { name: "Łódzkie", type: "Province" },
  'PL-LU': { name: "Lubelskie", type: "Province" },
  'PL-MA': { name: "Małopolskie", type: "Province" },
  'PL-MZ': { name: "Mazowieckie", type: "Province" },
  'PL-OP': { name: "Opolskie", type: "Province" },
  'PL-PD': { name: "Podlaskie", type: "Province" },
  'PL-PK': { name: "Podkarpackie", type: "Province" },
  'PL-PM': { name: "Pomorskie", type: "Province" },
  'PL-SK': { name: "Świętokrzyskie", type: "Province" },
  'PL-SL': { name: "Śląskie", type: "Province" },
  'PL-WN': { name: "Warmińsko-mazurskie", type: "Province" },
  'PL-WP': { name: "Wielkopolskie", type: "Province" },
  'PL-ZP': { name: "Zachodniopomorskie", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
