// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PM';
export const countryName = "St. Pierre & Miquelon";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PM-PM': { name: "St. Pierre & Miquelon", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
