// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PN';
export const countryName = "Pitcairn";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PN-PN': { name: "Pitcairn", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
