// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PR';
export const countryName = "Puerto Rico";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PR-PR': { name: "Puerto Rico", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
