// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PS';
export const countryName = "Palestine";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PS-BTH': { name: "Bayt Laḩm", type: "Governorate" },
  'PS-DEB': { name: "Dayr al Balaḩ", type: "Governorate" },
  'PS-GZA': { name: "Gaza", type: "Governorate" },
  'PS-HBN': { name: "Al Khalīl", type: "Governorate" },
  'PS-JEM': { name: "Al Quds", type: "Governorate" },
  'PS-JEN': { name: "Janīn", type: "Governorate" },
  'PS-JRH': { name: "Arīḩā wa al Aghwār", type: "Governorate" },
  'PS-KYS': { name: "Khan Yunis", type: "Governorate" },
  'PS-NBS': { name: "Nablus", type: "Governorate" },
  'PS-NGZ': { name: "North Gaza", type: "Governorate" },
  'PS-QQA': { name: "Qalqilya", type: "Governorate" },
  'PS-RBH': { name: "Ramallah", type: "Governorate" },
  'PS-RFH': { name: "Rafah", type: "Governorate" },
  'PS-SLT': { name: "Salfit", type: "Governorate" },
  'PS-TBS': { name: "Tubas", type: "Governorate" },
  'PS-TKM': { name: "Tulkarm", type: "Governorate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
