// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PT';
export const countryName = "Portugal";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PT-01': { name: "Aveiro", type: "District" },
  'PT-02': { name: "Beja", type: "District" },
  'PT-03': { name: "Braga", type: "District" },
  'PT-04': { name: "Bragança", type: "District" },
  'PT-05': { name: "Castelo Branco", type: "District" },
  'PT-06': { name: "Coimbra", type: "District" },
  'PT-07': { name: "Évora", type: "District" },
  'PT-08': { name: "Faro", type: "District" },
  'PT-09': { name: "Guarda", type: "District" },
  'PT-10': { name: "Leiria", type: "District" },
  'PT-11': { name: "Lisboa", type: "District" },
  'PT-12': { name: "Portalegre", type: "District" },
  'PT-13': { name: "Porto", type: "District" },
  'PT-14': { name: "Santarém", type: "District" },
  'PT-15': { name: "Setúbal", type: "District" },
  'PT-16': { name: "Viana do Castelo", type: "District" },
  'PT-17': { name: "Vila Real", type: "District" },
  'PT-18': { name: "Viseu", type: "District" },
  'PT-20': { name: "Região Autónoma dos Açores", type: "Autonomous region" },
  'PT-30': { name: "Região Autónoma da Madeira", type: "Autonomous region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
