// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PW';
export const countryName = "Palau";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PW-002': { name: "Aimeliik", type: "State" },
  'PW-004': { name: "Airai", type: "State" },
  'PW-010': { name: "Angaur", type: "State" },
  'PW-050': { name: "Hatobohei", type: "State" },
  'PW-100': { name: "Kayangel", type: "State" },
  'PW-150': { name: "Koror", type: "State" },
  'PW-212': { name: "Melekeok", type: "State" },
  'PW-214': { name: "Ngaraard", type: "State" },
  'PW-218': { name: "Ngarchelong", type: "State" },
  'PW-222': { name: "Ngardmau", type: "State" },
  'PW-224': { name: "Ngatpang", type: "State" },
  'PW-226': { name: "Ngchesar", type: "State" },
  'PW-227': { name: "Ngeremlengui", type: "State" },
  'PW-228': { name: "Ngiwal", type: "State" },
  'PW-350': { name: "Peleliu", type: "State" },
  'PW-370': { name: "Sonsorol", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
