// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'PY';
export const countryName = "Paraguay";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'PY-1': { name: "Concepción", type: "Department" },
  'PY-10': { name: "Alto Paraná", type: "Department" },
  'PY-11': { name: "Central", type: "Department" },
  'PY-12': { name: "Ñeembucú", type: "Department" },
  'PY-13': { name: "Amambay", type: "Department" },
  'PY-14': { name: "Canindeyú", type: "Department" },
  'PY-15': { name: "Presidente Hayes", type: "Department" },
  'PY-16': { name: "Alto Paraguay", type: "Department" },
  'PY-19': { name: "Boquerón", type: "Department" },
  'PY-2': { name: "San Pedro", type: "Department" },
  'PY-3': { name: "Cordillera", type: "Department" },
  'PY-4': { name: "Guairá", type: "Department" },
  'PY-5': { name: "Caaguazú", type: "Department" },
  'PY-6': { name: "Caazapá", type: "Department" },
  'PY-7': { name: "Itapúa", type: "Department" },
  'PY-8': { name: "Misiones", type: "Department" },
  'PY-9': { name: "Paraguarí", type: "Department" },
  'PY-ASU': { name: "Asunción", type: "Capital" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
