// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'QA';
export const countryName = "Qatar";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'QA-DA': { name: "Ad Dawḩah", type: "Municipality" },
  'QA-KH': { name: "Al Khawr wa adh Dhakhīrah", type: "Municipality" },
  'QA-MS': { name: "Ash Shamāl", type: "Municipality" },
  'QA-RA': { name: "Ar Rayyān", type: "Municipality" },
  'QA-US': { name: "Umm Şalāl", type: "Municipality" },
  'QA-WA': { name: "Al Wakrah", type: "Municipality" },
  'QA-ZA': { name: "Az̧ Z̧a‘āyin", type: "Municipality" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
