// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'RE';
export const countryName = "Reunion";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'RE-RE': { name: "Reunion", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
