// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'RO';
export const countryName = "Romania";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'RO-AB': { name: "Alba", type: "Department" },
  'RO-AG': { name: "Argeş", type: "Department" },
  'RO-AR': { name: "Arad", type: "Department" },
  'RO-B': { name: "Bucureşti", type: "Municipality" },
  'RO-BC': { name: "Bacău", type: "Department" },
  'RO-BH': { name: "Bihor", type: "Department" },
  'RO-BN': { name: "Bistriţa-Năsăud", type: "Department" },
  'RO-BR': { name: "Brăila", type: "Department" },
  'RO-BT': { name: "Botoşani", type: "Department" },
  'RO-BV': { name: "Braşov", type: "Department" },
  'RO-BZ': { name: "Buzău", type: "Department" },
  'RO-CJ': { name: "Cluj", type: "Department" },
  'RO-CL': { name: "Călăraşi", type: "Department" },
  'RO-CS': { name: "Caraş-Severin", type: "Department" },
  'RO-CT': { name: "Constanţa", type: "Department" },
  'RO-CV': { name: "Covasna", type: "Department" },
  'RO-DB': { name: "Dâmboviţa", type: "Department" },
  'RO-DJ': { name: "Dolj", type: "Department" },
  'RO-GJ': { name: "Gorj", type: "Department" },
  'RO-GL': { name: "Galaţi", type: "Department" },
  'RO-GR': { name: "Giurgiu", type: "Department" },
  'RO-HD': { name: "Hunedoara", type: "Department" },
  'RO-HR': { name: "Harghita", type: "Department" },
  'RO-IF': { name: "Ilfov", type: "Department" },
  'RO-IL': { name: "Ialomiţa", type: "Department" },
  'RO-IS': { name: "Iaşi", type: "Department" },
  'RO-MH': { name: "Mehedinţi", type: "Department" },
  'RO-MM': { name: "Maramureş", type: "Department" },
  'RO-MS': { name: "Mureş", type: "Department" },
  'RO-NT': { name: "Neamţ", type: "Department" },
  'RO-OT': { name: "Olt", type: "Department" },
  'RO-PH': { name: "Prahova", type: "Department" },
  'RO-SB': { name: "Sibiu", type: "Department" },
  'RO-SJ': { name: "Sălaj", type: "Department" },
  'RO-SM': { name: "Satu Mare", type: "Department" },
  'RO-SV': { name: "Suceava", type: "Department" },
  'RO-TL': { name: "Tulcea", type: "Department" },
  'RO-TM': { name: "Timiş", type: "Department" },
  'RO-TR': { name: "Teleorman", type: "Department" },
  'RO-VL': { name: "Vâlcea", type: "Department" },
  'RO-VN': { name: "Vrancea", type: "Department" },
  'RO-VS': { name: "Vaslui", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
