// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'RS';
export const countryName = "Serbia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'RS-00': { name: "Beograd", type: "City" },
  'RS-01': { name: "Severnobački okrug", type: "District" },
  'RS-02': { name: "Srednjebanatski okrug", type: "District" },
  'RS-03': { name: "Severnobanatski okrug", type: "District" },
  'RS-04': { name: "Južnobanatski okrug", type: "District" },
  'RS-05': { name: "Zapadnobački okrug", type: "District" },
  'RS-06': { name: "Južnobački okrug", type: "District" },
  'RS-07': { name: "Sremski okrug", type: "District" },
  'RS-08': { name: "Mačvanski okrug", type: "District" },
  'RS-09': { name: "Kolubarski okrug", type: "District" },
  'RS-10': { name: "Podunavski okrug", type: "District" },
  'RS-11': { name: "Braničevski okrug", type: "District" },
  'RS-12': { name: "Šumadijski okrug", type: "District" },
  'RS-13': { name: "Pomoravski okrug", type: "District" },
  'RS-14': { name: "Borski okrug", type: "District" },
  'RS-15': { name: "Zaječarski okrug", type: "District" },
  'RS-16': { name: "Zlatiborski okrug", type: "District" },
  'RS-17': { name: "Moravički okrug", type: "District" },
  'RS-18': { name: "Raški okrug", type: "District" },
  'RS-19': { name: "Rasinski okrug", type: "District" },
  'RS-20': { name: "Nišavski okrug", type: "District" },
  'RS-21': { name: "Toplički okrug", type: "District" },
  'RS-22': { name: "Pirotski okrug", type: "District" },
  'RS-23': { name: "Jablanički okrug", type: "District" },
  'RS-24': { name: "Pčinjski okrug", type: "District" },
  'RS-25': { name: "Kosovski okrug", type: "District" },
  'RS-26': { name: "Pećki okrug", type: "District" },
  'RS-27': { name: "Prizrenski okrug", type: "District" },
  'RS-28': { name: "Kosovsko-Mitrovački okrug", type: "District" },
  'RS-29': { name: "Kosovsko-Pomoravski okrug", type: "District" },
  'RS-KM': { name: "Kosovo-Metohija", type: "Autonomous province" },
  'RS-VO': { name: "Vojvodina", type: "Autonomous province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
