// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'RW';
export const countryName = "Rwanda";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'RW-01': { name: "Ville de Kigal", type: "Town council" },
  'RW-02': { name: "Est", type: "Province" },
  'RW-03': { name: "Nord", type: "Province" },
  'RW-04': { name: "Ouest", type: "Province" },
  'RW-05': { name: "Sud", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
