// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SA';
export const countryName = "Saudi Arabia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SA-01': { name: "Ar Riyāḑ", type: "Province" },
  'SA-02': { name: "Makkah al Mukarramah", type: "Province" },
  'SA-03': { name: "Al Madīnah al Munawwarah", type: "Province" },
  'SA-04': { name: "Ash Sharqīyah", type: "Province" },
  'SA-05': { name: "Al Qaşīm", type: "Province" },
  'SA-06': { name: "Ḩā'il", type: "Province" },
  'SA-07': { name: "Tabūk", type: "Province" },
  'SA-08': { name: "Al Ḩudūd ash Shamālīyah", type: "Province" },
  'SA-09': { name: "Jāzān", type: "Province" },
  'SA-10': { name: "Najrān", type: "Province" },
  'SA-11': { name: "Al Bāḩah", type: "Province" },
  'SA-12': { name: "Al Jawf", type: "Province" },
  'SA-14': { name: "'Asīr", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
