// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SB';
export const countryName = "Solomon Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SB-CE': { name: "Central", type: "Province" },
  'SB-CH': { name: "Choiseul", type: "Province" },
  'SB-CT': { name: "Capital Territory", type: "Capital territory" },
  'SB-GU': { name: "Guadalcanal", type: "Province" },
  'SB-IS': { name: "Isabel", type: "Province" },
  'SB-MK': { name: "Makira-Ulawa", type: "Province" },
  'SB-ML': { name: "Malaita", type: "Province" },
  'SB-RB': { name: "Rennell and Bellona", type: "Province" },
  'SB-TE': { name: "Temotu", type: "Province" },
  'SB-WE': { name: "Western", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
