// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SC';
export const countryName = "Seychelles";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SC-01': { name: "Anse aux Pins", type: "District" },
  'SC-02': { name: "Ans Bwalo", type: "District" },
  'SC-03': { name: "Anse Etoile", type: "District" },
  'SC-04': { name: "Au Cap", type: "District" },
  'SC-05': { name: "Anse Royale", type: "District" },
  'SC-06': { name: "Baie Lazare", type: "District" },
  'SC-07': { name: "Baie Sainte-Anne", type: "District" },
  'SC-08': { name: "Beau Vallon", type: "District" },
  'SC-09': { name: "Bel Air", type: "District" },
  'SC-10': { name: "Bel Ombre", type: "District" },
  'SC-11': { name: "Cascade", type: "District" },
  'SC-12': { name: "Glacis", type: "District" },
  'SC-13': { name: "Grand'Anse Mahé", type: "District" },
  'SC-14': { name: "Grand'Anse Praslin", type: "District" },
  'SC-15': { name: "Ladig", type: "District" },
  'SC-16': { name: "English River", type: "District" },
  'SC-17': { name: "Mon Bikston", type: "District" },
  'SC-18': { name: "Mon Fleri", type: "District" },
  'SC-19': { name: "Plaisance", type: "District" },
  'SC-20': { name: "Pointe La Rue", type: "District" },
  'SC-21': { name: "Porglo", type: "District" },
  'SC-22': { name: "Saint Louis", type: "District" },
  'SC-23': { name: "Takamaka", type: "District" },
  'SC-24': { name: "Lemamel", type: "District" },
  'SC-25': { name: "Roche Caïman", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
