// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SD';
export const countryName = "Sudan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SD-DC': { name: "Central Darfur", type: "State" },
  'SD-DE': { name: "East Darfur", type: "State" },
  'SD-DN': { name: "North Darfur", type: "State" },
  'SD-DS': { name: "Janūb Dārfūr", type: "State" },
  'SD-DW': { name: "Gharb Dārfūr", type: "State" },
  'SD-GD': { name: "Al Qaḑārif", type: "State" },
  'SD-GZ': { name: "Al Jazīrah", type: "State" },
  'SD-KA': { name: "Kassala", type: "State" },
  'SD-KH': { name: "Al Kharţūm", type: "State" },
  'SD-KN': { name: "North Kordofan", type: "State" },
  'SD-KS': { name: "Janūb Kurdufān", type: "State" },
  'SD-NB': { name: "An Nīl al Azraq", type: "State" },
  'SD-NO': { name: "Ash Shamālīyah", type: "State" },
  'SD-NR': { name: "An Nīl", type: "State" },
  'SD-NW': { name: "An Nīl al Abyaḑ", type: "State" },
  'SD-RS': { name: "Al Baḩr al Aḩmar", type: "State" },
  'SD-SI': { name: "Sennar", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
