// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SE';
export const countryName = "Sweden";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SE-AB': { name: "Stockholms län", type: "County" },
  'SE-AC': { name: "Västerbottens län", type: "County" },
  'SE-BD': { name: "Norrbottens län", type: "County" },
  'SE-C': { name: "Uppsala län", type: "County" },
  'SE-D': { name: "Södermanlands län", type: "County" },
  'SE-E': { name: "Östergötlands län", type: "County" },
  'SE-F': { name: "Jönköpings län", type: "County" },
  'SE-G': { name: "Kronobergs län", type: "County" },
  'SE-H': { name: "Kalmar län", type: "County" },
  'SE-I': { name: "Gotlands län", type: "County" },
  'SE-K': { name: "Blekinge län", type: "County" },
  'SE-M': { name: "Skåne län", type: "County" },
  'SE-N': { name: "Hallands län", type: "County" },
  'SE-O': { name: "Västra Götalands län", type: "County" },
  'SE-S': { name: "Värmlands län", type: "County" },
  'SE-T': { name: "Örebro län", type: "County" },
  'SE-U': { name: "Västmanlands län", type: "County" },
  'SE-W': { name: "Dalarnas län", type: "County" },
  'SE-X': { name: "Gävleborgs län", type: "County" },
  'SE-Y': { name: "Västernorrlands län", type: "County" },
  'SE-Z': { name: "Jämtlands län", type: "County" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
