// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SG';
export const countryName = "Singapore";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SG-01': { name: "Central Singapore", type: "District" },
  'SG-02': { name: "North East", type: "District" },
  'SG-03': { name: "North West", type: "District" },
  'SG-04': { name: "South East", type: "District" },
  'SG-05': { name: "South West", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
