// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SH';
export const countryName = "Saint Helena, Ascension and Tristan Da Cunha";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SH-AC': { name: "Ascension", type: "Geographical entity" },
  'SH-HL': { name: "Saint Helena", type: "Geographical entity" },
  'SH-TA': { name: "Tristan da Cunha", type: "Geographical entity" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
