// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SJ';
export const countryName = "Svalbard & Jan Mayen Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SJ-SJ': { name: "Svalbard & Jan Mayen Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
