// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SK';
export const countryName = "Slovakia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SK-BC': { name: "Banskobystrický kraj", type: "Region" },
  'SK-BL': { name: "Bratislavský kraj", type: "Region" },
  'SK-KI': { name: "Košický kraj", type: "Region" },
  'SK-NI': { name: "Nitriansky kraj", type: "Region" },
  'SK-PV': { name: "Prešovský kraj", type: "Region" },
  'SK-TA': { name: "Trnavský kraj", type: "Region" },
  'SK-TC': { name: "Trenčiansky kraj", type: "Region" },
  'SK-ZI': { name: "Žilinský kraj", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
