// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SL';
export const countryName = "Sierra Leone";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SL-E': { name: "Eastern", type: "Province" },
  'SL-N': { name: "Northern", type: "Province" },
  'SL-S': { name: "Southern", type: "Province" },
  'SL-W': { name: "Western Area", type: "Area" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
