// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SM';
export const countryName = "San Marino";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SM-01': { name: "Acquaviva", type: "Municipality" },
  'SM-02': { name: "Chiesanuova", type: "Municipality" },
  'SM-03': { name: "Domagnano", type: "Municipality" },
  'SM-04': { name: "Faetano", type: "Municipality" },
  'SM-05': { name: "Fiorentino", type: "Municipality" },
  'SM-06': { name: "Borgo Maggiore", type: "Municipality" },
  'SM-07': { name: "San Marino", type: "Municipality" },
  'SM-08': { name: "Montegiardino", type: "Municipality" },
  'SM-09': { name: "Serravalle", type: "Municipality" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
