// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SN';
export const countryName = "Senegal";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SN-DB': { name: "Diourbel", type: "Region" },
  'SN-DK': { name: "Dakar", type: "Region" },
  'SN-FK': { name: "Fatick", type: "Region" },
  'SN-KA': { name: "Kaffrine", type: "Region" },
  'SN-KD': { name: "Kolda", type: "Region" },
  'SN-KE': { name: "Kédougou", type: "Region" },
  'SN-KL': { name: "Kaolack", type: "Region" },
  'SN-LG': { name: "Louga", type: "Region" },
  'SN-MT': { name: "Matam", type: "Region" },
  'SN-SE': { name: "Sédhiou", type: "Region" },
  'SN-SL': { name: "Saint-Louis", type: "Region" },
  'SN-TC': { name: "Tambacounda", type: "Region" },
  'SN-TH': { name: "Thiès", type: "Region" },
  'SN-ZG': { name: "Ziguinchor", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
