// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SO';
export const countryName = "Somalia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SO-AW': { name: "Awdal", type: "Region" },
  'SO-BK': { name: "Bakool", type: "Region" },
  'SO-BN': { name: "Banaadir", type: "Region" },
  'SO-BR': { name: "Bari", type: "Region" },
  'SO-BY': { name: "Bay", type: "Region" },
  'SO-GA': { name: "Galguduud", type: "Region" },
  'SO-GE': { name: "Gedo", type: "Region" },
  'SO-HI': { name: "Hiiraan", type: "Region" },
  'SO-JD': { name: "Jubbada Dhexe", type: "Region" },
  'SO-JH': { name: "Jubbada Hoose", type: "Region" },
  'SO-MU': { name: "Mudug", type: "Region" },
  'SO-NU': { name: "Nugaal", type: "Region" },
  'SO-SA': { name: "Sanaag", type: "Region" },
  'SO-SD': { name: "Shabeellaha Dhexe", type: "Region" },
  'SO-SH': { name: "Shabeellaha Hoose", type: "Region" },
  'SO-SO': { name: "Sool", type: "Region" },
  'SO-TO': { name: "Togdheer", type: "Region" },
  'SO-WO': { name: "Woqooyi Galbeed", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
