// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SR';
export const countryName = "Suriname";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SR-BR': { name: "Brokopondo", type: "District" },
  'SR-CM': { name: "Commewijne", type: "District" },
  'SR-CR': { name: "Coronie", type: "District" },
  'SR-MA': { name: "Marowijne", type: "District" },
  'SR-NI': { name: "Nickerie", type: "District" },
  'SR-PM': { name: "Paramaribo", type: "District" },
  'SR-PR': { name: "Para", type: "District" },
  'SR-SA': { name: "Saramacca", type: "District" },
  'SR-SI': { name: "Sipaliwini", type: "District" },
  'SR-WA': { name: "Wanica", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
