// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SS';
export const countryName = "South Sudan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SS-BN': { name: "Northern Bahr el Ghazal", type: "State" },
  'SS-BW': { name: "Western Bahr el Ghazal", type: "State" },
  'SS-EC': { name: "Central Equatoria", type: "State" },
  'SS-EE': { name: "Eastern Equatoria", type: "State" },
  'SS-EW': { name: "Western Equatoria", type: "State" },
  'SS-JG': { name: "Jonglei", type: "State" },
  'SS-LK': { name: "Lakes", type: "State" },
  'SS-NU': { name: "Upper Nile", type: "State" },
  'SS-UY': { name: "Unity", type: "State" },
  'SS-WR': { name: "Warrap", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
