// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'ST';
export const countryName = "Sao Tome and Principe";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'ST-P': { name: "Príncipe", type: "Province" },
  'ST-S': { name: "São Tomé", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
