// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SV';
export const countryName = "El Salvador";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SV-AH': { name: "Ahuachapán", type: "Department" },
  'SV-CA': { name: "Cabañas", type: "Department" },
  'SV-CH': { name: "Chalatenango", type: "Department" },
  'SV-CU': { name: "Cuscatlán", type: "Department" },
  'SV-LI': { name: "La Libertad", type: "Department" },
  'SV-MO': { name: "Morazán", type: "Department" },
  'SV-PA': { name: "La Paz", type: "Department" },
  'SV-SA': { name: "Santa Ana", type: "Department" },
  'SV-SM': { name: "San Miguel", type: "Department" },
  'SV-SO': { name: "Sonsonate", type: "Department" },
  'SV-SS': { name: "San Salvador", type: "Department" },
  'SV-SV': { name: "San Vicente", type: "Department" },
  'SV-UN': { name: "La Unión", type: "Department" },
  'SV-US': { name: "Usulután", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
