// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SX';
export const countryName = "St. Maarten";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SX-SX': { name: "St. Maarten", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
