// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SY';
export const countryName = "Syria";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SY-DI': { name: "Dimashq", type: "Province" },
  'SY-DR': { name: "Dar'ā", type: "Province" },
  'SY-DY': { name: "Dayr az Zawr", type: "Province" },
  'SY-HA': { name: "Al Ḩasakah", type: "Province" },
  'SY-HI': { name: "Ḩimş", type: "Province" },
  'SY-HL': { name: "Ḩalab", type: "Province" },
  'SY-HM': { name: "Ḩamāh", type: "Province" },
  'SY-ID': { name: "Idlib", type: "Province" },
  'SY-LA': { name: "Al Lādhiqīyah", type: "Province" },
  'SY-QU': { name: "Al Qunayţirah", type: "Province" },
  'SY-RA': { name: "Ar Raqqah", type: "Province" },
  'SY-RD': { name: "Rīf Dimashq", type: "Province" },
  'SY-SU': { name: "As Suwaydā'", type: "Province" },
  'SY-TA': { name: "Ţarţūs", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
