// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'SZ';
export const countryName = "Swaziland";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'SZ-HH': { name: "Hhohho", type: "District" },
  'SZ-LU': { name: "Lubombo", type: "District" },
  'SZ-MA': { name: "Manzini", type: "District" },
  'SZ-SH': { name: "Shiselweni", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
