// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TC';
export const countryName = "Turks & Caicos Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TC-TC': { name: "Turks & Caicos Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
