// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TD';
export const countryName = "Chad";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TD-BA': { name: "Al Baţḩah", type: "Region" },
  'TD-BG': { name: "Baḩr al Ghazāl", type: "Region" },
  'TD-BO': { name: "Borkou", type: "Region" },
  'TD-CB': { name: "Chari-Baguirmi", type: "Region" },
  'TD-EE': { name: "Ennedi-Est", type: "Region" },
  'TD-EO': { name: "Ennedi-Ouest", type: "Region" },
  'TD-GR': { name: "Guéra", type: "Region" },
  'TD-HL': { name: "Hadjer Lamis", type: "Region" },
  'TD-KA': { name: "Kanem", type: "Region" },
  'TD-LC': { name: "Al Buḩayrah", type: "Region" },
  'TD-LO': { name: "Logone-Occidental", type: "Region" },
  'TD-LR': { name: "Logone-Oriental", type: "Region" },
  'TD-MA': { name: "Mandoul", type: "Region" },
  'TD-MC': { name: "Moyen-Chari", type: "Region" },
  'TD-ME': { name: "Mayo-Kebbi-Est", type: "Region" },
  'TD-MO': { name: "Mayo-Kebbi-Ouest", type: "Region" },
  'TD-ND': { name: "Madīnat Injamīnā", type: "Region" },
  'TD-OD': { name: "Ouaddaï", type: "Region" },
  'TD-SA': { name: "Salamat", type: "Region" },
  'TD-SI': { name: "Sila", type: "Region" },
  'TD-TA': { name: "Tandjilé", type: "Region" },
  'TD-TI': { name: "Tibastī", type: "Region" },
  'TD-WF': { name: "Wadi Fira", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
