// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TF';
export const countryName = "French Southern Territories";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TF-TF': { name: "French Southern Territories", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
