// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TG';
export const countryName = "Togo";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TG-C': { name: "Centre", type: "Region" },
  'TG-K': { name: "Kara", type: "Region" },
  'TG-M': { name: "Maritime", type: "Region" },
  'TG-P': { name: "Plateaux", type: "Region" },
  'TG-S': { name: "Savannes", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
