// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TJ';
export const countryName = "Tajikistan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TJ-DU': { name: "Dushanbe", type: "Capital territory" },
  'TJ-GB': { name: "Kŭhistoni Badakhshon", type: "Autonomous region" },
  'TJ-KT': { name: "Khatlon", type: "Region" },
  'TJ-SU': { name: "Sughd", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
