// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TK';
export const countryName = "Tokelau";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TK-TK': { name: "Tokelau", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
