// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TL';
export const countryName = "East Timor";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TL-AL': { name: "Aileu", type: "District" },
  'TL-AN': { name: "Ainaro", type: "District" },
  'TL-BA': { name: "Baucau", type: "District" },
  'TL-BO': { name: "Bobonaro", type: "District" },
  'TL-CO': { name: "Cova Lima", type: "District" },
  'TL-DI': { name: "Díli", type: "District" },
  'TL-ER': { name: "Ermera", type: "District" },
  'TL-LA': { name: "Lautém", type: "District" },
  'TL-LI': { name: "Likisá", type: "District" },
  'TL-MF': { name: "Manufahi", type: "District" },
  'TL-MT': { name: "Manatuto", type: "District" },
  'TL-OE': { name: "Oecussi", type: "District" },
  'TL-VI': { name: "Vikeke", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
