// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TM';
export const countryName = "Turkmenistan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TM-A': { name: "Ahal", type: "Region" },
  'TM-B': { name: "Balkan", type: "Region" },
  'TM-D': { name: "Daşoguz", type: "Region" },
  'TM-L': { name: "Lebap", type: "Region" },
  'TM-M': { name: "Mary", type: "Region" },
  'TM-S': { name: "Aşgabat", type: "City" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
