// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TN';
export const countryName = "Tunisia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TN-11': { name: "Tunis", type: "Governorate" },
  'TN-12': { name: "Ariana", type: "Governorate" },
  'TN-13': { name: "Ben Arous", type: "Governorate" },
  'TN-14': { name: "La Manouba", type: "Governorate" },
  'TN-21': { name: "Nabeul", type: "Governorate" },
  'TN-22': { name: "Zaghouan", type: "Governorate" },
  'TN-23': { name: "Bizerte", type: "Governorate" },
  'TN-31': { name: "Béja", type: "Governorate" },
  'TN-32': { name: "Jendouba", type: "Governorate" },
  'TN-33': { name: "Le Kef", type: "Governorate" },
  'TN-34': { name: "Siliana", type: "Governorate" },
  'TN-41': { name: "Kairouan", type: "Governorate" },
  'TN-42': { name: "Kasserine", type: "Governorate" },
  'TN-43': { name: "Sidi Bouzid", type: "Governorate" },
  'TN-51': { name: "Sousse", type: "Governorate" },
  'TN-52': { name: "Monastir", type: "Governorate" },
  'TN-53': { name: "Mahdia", type: "Governorate" },
  'TN-61': { name: "Sfax", type: "Governorate" },
  'TN-71': { name: "Gafsa", type: "Governorate" },
  'TN-72': { name: "Tozeur", type: "Governorate" },
  'TN-73': { name: "Kebili", type: "Governorate" },
  'TN-81': { name: "Gabès", type: "Governorate" },
  'TN-82': { name: "Medenine", type: "Governorate" },
  'TN-83': { name: "Tataouine", type: "Governorate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
