// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TO';
export const countryName = "Tonga";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TO-01': { name: "'Eua", type: "Division" },
  'TO-02': { name: "Ha'apai", type: "Division" },
  'TO-03': { name: "Niuas", type: "Division" },
  'TO-04': { name: "Tongatapu", type: "Division" },
  'TO-05': { name: "Vava'u", type: "Division" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
