// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TT';
export const countryName = "Trinidad and Tobago";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TT-ARI': { name: "Arima", type: "Municipality" },
  'TT-CHA': { name: "Chaguanas", type: "Municipality" },
  'TT-CTT': { name: "Couva-Tabaquite-Talparo", type: "Region" },
  'TT-DMN': { name: "Diego Martin", type: "Region" },
  'TT-ETO': { name: "Eastern Tobago", type: "Region" },
  'TT-PED': { name: "Penal-Debe", type: "Region" },
  'TT-POS': { name: "Port of Spain", type: "Municipality" },
  'TT-PRT': { name: "Princes Town", type: "Region" },
  'TT-PTF': { name: "Point Fortin", type: "Municipality" },
  'TT-RCM': { name: "Rio Claro-Mayaro", type: "Region" },
  'TT-SFO': { name: "San Fernando", type: "Municipality" },
  'TT-SGE': { name: "Sangre Grande", type: "Region" },
  'TT-SIP': { name: "Siparia", type: "Region" },
  'TT-SJL': { name: "San Juan-Laventille", type: "Region" },
  'TT-TUP': { name: "Tunapuna-Piarco", type: "Region" },
  'TT-WTO': { name: "Western Tobago", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
