// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TV';
export const countryName = "Tuvalu";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TV-FUN': { name: "Funafuti", type: "Town council" },
  'TV-NIT': { name: "Niutao", type: "Island council" },
  'TV-NKF': { name: "Nukufetau", type: "Island council" },
  'TV-NKL': { name: "Nukulaelae", type: "Island council" },
  'TV-NMA': { name: "Nanumea", type: "Island council" },
  'TV-NMG': { name: "Nanumanga", type: "Island council" },
  'TV-NUI': { name: "Nui", type: "Island council" },
  'TV-VAI': { name: "Vaitupu", type: "Island council" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
