// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TW';
export const countryName = "Taiwan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TW-CHA': { name: "Changhua", type: "District" },
  'TW-CYI': { name: "Chiayi", type: "Municipality" },
  'TW-CYQ': { name: "Chiayi", type: "District" },
  'TW-HSQ': { name: "Hsinchu", type: "District" },
  'TW-HSZ': { name: "Hsinchu", type: "Municipality" },
  'TW-HUA': { name: "Hualien", type: "District" },
  'TW-ILA': { name: "Ilan", type: "District" },
  'TW-KEE': { name: "Keelung", type: "Municipality" },
  'TW-KHH': { name: "Kaohsiung", type: "Special municipality" },
  'TW-KHQ': { name: "Kaohsiung", type: "District" },
  'TW-MIA': { name: "Miaoli", type: "District" },
  'TW-NAN': { name: "Nantou", type: "District" },
  'TW-PEN': { name: "Penghu", type: "District" },
  'TW-PIF': { name: "Pingtung", type: "District" },
  'TW-TAO': { name: "Taoyuan", type: "District" },
  'TW-TNN': { name: "Tainan", type: "Municipality" },
  'TW-TNQ': { name: "Tainan", type: "District" },
  'TW-TPE': { name: "Taipei", type: "Special municipality" },
  'TW-TPQ': { name: "Taipei", type: "District" },
  'TW-TTT': { name: "Taitung", type: "District" },
  'TW-TXG': { name: "Taichung", type: "Municipality" },
  'TW-TXQ': { name: "Taichung", type: "District" },
  'TW-YUN': { name: "Yunlin", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
