// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'TZ';
export const countryName = "Tanzania";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'TZ-01': { name: "Arusha", type: "Region" },
  'TZ-02': { name: "Dar es Salaam", type: "Region" },
  'TZ-03': { name: "Dodoma", type: "Region" },
  'TZ-04': { name: "Iringa", type: "Region" },
  'TZ-05': { name: "Kagera", type: "Region" },
  'TZ-06': { name: "Kaskazini Pemba", type: "Region" },
  'TZ-07': { name: "Kaskazini Unguja", type: "Region" },
  'TZ-08': { name: "Kigoma", type: "Region" },
  'TZ-09': { name: "Kilimanjaro", type: "Region" },
  'TZ-10': { name: "Kusini Pemba", type: "Region" },
  'TZ-11': { name: "Kusini Unguja", type: "Region" },
  'TZ-12': { name: "Lindi", type: "Region" },
  'TZ-13': { name: "Mara", type: "Region" },
  'TZ-14': { name: "Mbeya", type: "Region" },
  'TZ-15': { name: "Mjini Magharibi", type: "Region" },
  'TZ-16': { name: "Morogoro", type: "Region" },
  'TZ-17': { name: "Mtwara", type: "Region" },
  'TZ-18': { name: "Mwanza", type: "Region" },
  'TZ-19': { name: "Coast", type: "Region" },
  'TZ-20': { name: "Rukwa", type: "Region" },
  'TZ-21': { name: "Ruvuma", type: "Region" },
  'TZ-22': { name: "Shinyanga", type: "Region" },
  'TZ-23': { name: "Singida", type: "Region" },
  'TZ-24': { name: "Tabora", type: "Region" },
  'TZ-25': { name: "Tanga", type: "Region" },
  'TZ-26': { name: "Manyara", type: "Region" },
  'TZ-27': { name: "Geita", type: "Region" },
  'TZ-28': { name: "Katavi", type: "Region" },
  'TZ-29': { name: "Njombe", type: "Region" },
  'TZ-30': { name: "Simiyu", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
