// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'UA';
export const countryName = "Ukraine";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'UA-05': { name: "Vinnytska oblast", type: "Region" },
  'UA-07': { name: "Volynska oblast", type: "Region" },
  'UA-09': { name: "Luhanska oblast", type: "Region" },
  'UA-12': { name: "Dnipropetrovska oblast", type: "Region" },
  'UA-14': { name: "Donetska oblast", type: "Region" },
  'UA-18': { name: "Zhytomyrska oblast", type: "Region" },
  'UA-21': { name: "Zakarpatska oblast", type: "Region" },
  'UA-23': { name: "Zaporizka oblast", type: "Region" },
  'UA-26': { name: "Ivano-Frankivska oblast", type: "Region" },
  'UA-30': { name: "Kyiv", type: "City" },
  'UA-32': { name: "Kyivska oblast", type: "Region" },
  'UA-35': { name: "Kirovohradska oblast", type: "Region" },
  'UA-40': { name: "Sevastopol", type: "City" },
  'UA-43': { name: "Avtonomna Respublika Krym", type: "Republic" },
  'UA-46': { name: "Lvivska oblast", type: "Region" },
  'UA-48': { name: "Mykolaivska oblast", type: "Region" },
  'UA-51': { name: "Odeska oblast", type: "Region" },
  'UA-53': { name: "Poltavska oblast", type: "Region" },
  'UA-56': { name: "Rivnenska oblast", type: "Region" },
  'UA-59': { name: "Sumska oblast", type: "Region" },
  'UA-61': { name: "Ternopilska oblast", type: "Region" },
  'UA-63': { name: "Kharkivska oblast", type: "Region" },
  'UA-65': { name: "Khersonska oblast", type: "Region" },
  'UA-68': { name: "Khmelnytska oblast", type: "Region" },
  'UA-71': { name: "Cherkaska oblast", type: "Region" },
  'UA-74': { name: "Chernihivska oblast", type: "Region" },
  'UA-77': { name: "Chernivetska oblast", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
