// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'UM';
export const countryName = "United States Minor Outlying Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'UM-67': { name: "Johnston Atoll", type: "Islands, groups of islands" },
  'UM-71': { name: "Midway Islands", type: "Islands, groups of islands" },
  'UM-76': { name: "Navassa Island", type: "Islands, groups of islands" },
  'UM-79': { name: "Wake Island", type: "Islands, groups of islands" },
  'UM-81': { name: "Baker Island", type: "Islands, groups of islands" },
  'UM-84': { name: "Howland Island", type: "Islands, groups of islands" },
  'UM-86': { name: "Jarvis Island", type: "Islands, groups of islands" },
  'UM-89': { name: "Kingman Reef", type: "Islands, groups of islands" },
  'UM-95': { name: "Palmyra Atoll", type: "Islands, groups of islands" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
