// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'UY';
export const countryName = "Uruguay";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'UY-AR': { name: "Artigas", type: "Department" },
  'UY-CA': { name: "Canelones", type: "Department" },
  'UY-CL': { name: "Cerro Largo", type: "Department" },
  'UY-CO': { name: "Colonia", type: "Department" },
  'UY-DU': { name: "Durazno", type: "Department" },
  'UY-FD': { name: "Florida", type: "Department" },
  'UY-FS': { name: "Flores", type: "Department" },
  'UY-LA': { name: "Lavalleja", type: "Department" },
  'UY-MA': { name: "Maldonado", type: "Department" },
  'UY-MO': { name: "Montevideo", type: "Department" },
  'UY-PA': { name: "Paysandú", type: "Department" },
  'UY-RN': { name: "Río Negro", type: "Department" },
  'UY-RO': { name: "Rocha", type: "Department" },
  'UY-RV': { name: "Rivera", type: "Department" },
  'UY-SA': { name: "Salto", type: "Department" },
  'UY-SJ': { name: "San José", type: "Department" },
  'UY-SO': { name: "Soriano", type: "Department" },
  'UY-TA': { name: "Tacuarembó", type: "Department" },
  'UY-TT': { name: "Treinta y Tres", type: "Department" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
