// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'UZ';
export const countryName = "Uzbekistan";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'UZ-AN': { name: "Andijon", type: "Region" },
  'UZ-BU': { name: "Buxoro", type: "Region" },
  'UZ-FA': { name: "Farg‘ona", type: "Region" },
  'UZ-JI': { name: "Jizzax", type: "Region" },
  'UZ-NG': { name: "Namangan", type: "Region" },
  'UZ-NW': { name: "Navoiy", type: "Region" },
  'UZ-QA': { name: "Qashqadaryo", type: "Region" },
  'UZ-QR': { name: "Qoraqalpog‘iston Respublikasi", type: "Republic" },
  'UZ-SA': { name: "Samarqand", type: "Region" },
  'UZ-SI': { name: "Sirdaryo", type: "Region" },
  'UZ-SU': { name: "Surxondaryo", type: "Region" },
  'UZ-TK': { name: "Toshkent", type: "City" },
  'UZ-TO': { name: "Toshkent", type: "Region" },
  'UZ-XO': { name: "Xorazm", type: "Region" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
