// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'VA';
export const countryName = "Vatican City";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'VA-VA': { name: "Vatican City", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
