// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'VC';
export const countryName = "Saint Vincent And The Grenadines";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'VC-01': { name: "Charlotte", type: "Parish" },
  'VC-02': { name: "Saint Andrew", type: "Parish" },
  'VC-03': { name: "Saint David", type: "Parish" },
  'VC-04': { name: "Saint George", type: "Parish" },
  'VC-05': { name: "Saint Patrick", type: "Parish" },
  'VC-06': { name: "Grenadines", type: "Parish" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
