// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'VE';
export const countryName = "Venezuela";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'VE-A': { name: "Distrito Capital", type: "Capital district" },
  'VE-B': { name: "Anzoátegui", type: "State" },
  'VE-C': { name: "Apure", type: "State" },
  'VE-D': { name: "Aragua", type: "State" },
  'VE-E': { name: "Barinas", type: "State" },
  'VE-F': { name: "Bolívar", type: "State" },
  'VE-G': { name: "Carabobo", type: "State" },
  'VE-H': { name: "Cojedes", type: "State" },
  'VE-I': { name: "Falcón", type: "State" },
  'VE-J': { name: "Guárico", type: "State" },
  'VE-K': { name: "Lara", type: "State" },
  'VE-L': { name: "Mérida", type: "State" },
  'VE-M': { name: "Miranda", type: "State" },
  'VE-N': { name: "Monagas", type: "State" },
  'VE-O': { name: "Nueva Esparta", type: "State" },
  'VE-P': { name: "Portuguesa", type: "State" },
  'VE-R': { name: "Sucre", type: "State" },
  'VE-S': { name: "Táchira", type: "State" },
  'VE-T': { name: "Trujillo", type: "State" },
  'VE-U': { name: "Yaracuy", type: "State" },
  'VE-V': { name: "Zulia", type: "State" },
  'VE-W': { name: "Dependencias Federales", type: "Federal dependency" },
  'VE-X': { name: "Vargas", type: "State" },
  'VE-Y': { name: "Delta Amacuro", type: "State" },
  'VE-Z': { name: "Amazonas", type: "State" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
