// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'VG';
export const countryName = "British Virgin Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'VG-VG': { name: "British Virgin Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
