// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'VI';
export const countryName = "Virgin Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'VI-VI': { name: "Virgin Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
