// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'VU';
export const countryName = "Vanuatu";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'VU-MAP': { name: "Malampa", type: "Province" },
  'VU-PAM': { name: "Pénama", type: "Province" },
  'VU-SAM': { name: "Sanma", type: "Province" },
  'VU-SEE': { name: "Shéfa", type: "Province" },
  'VU-TAE': { name: "Taféa", type: "Province" },
  'VU-TOB': { name: "Torba", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
