// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'WF';
export const countryName = "Wallis & Futuna Islands";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'WF-WF': { name: "Wallis & Futuna Islands", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
