// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'WS';
export const countryName = "Samoa";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'WS-AA': { name: "A'ana", type: "District" },
  'WS-AL': { name: "Aiga-i-le-Tai", type: "District" },
  'WS-AT': { name: "Atua", type: "District" },
  'WS-FA': { name: "Fa'asaleleaga", type: "District" },
  'WS-GE': { name: "Gaga'emauga", type: "District" },
  'WS-GI': { name: "Gagaifomauga", type: "District" },
  'WS-PA': { name: "Palauli", type: "District" },
  'WS-SA': { name: "Satupa'itea", type: "District" },
  'WS-TU': { name: "Tuamasaga", type: "District" },
  'WS-VF': { name: "Va'a-o-Fonoti", type: "District" },
  'WS-VS': { name: "Vaisigano", type: "District" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
