// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'YE';
export const countryName = "Yemen";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'YE-AB': { name: "Abyān", type: "Governorate" },
  'YE-AD': { name: "'Adan", type: "Governorate" },
  'YE-AM': { name: "'Amrān", type: "Governorate" },
  'YE-BA': { name: "Al Bayḑā'", type: "Governorate" },
  'YE-DA': { name: "Aḑ Ḑāli'", type: "Governorate" },
  'YE-DH': { name: "Dhamār", type: "Governorate" },
  'YE-HD': { name: "Ḩaḑramawt", type: "Governorate" },
  'YE-HJ': { name: "Ḩajjah", type: "Governorate" },
  'YE-HU': { name: "Al Ḩudaydah", type: "Governorate" },
  'YE-IB': { name: "Ibb", type: "Governorate" },
  'YE-JA': { name: "Al Jawf", type: "Governorate" },
  'YE-LA': { name: "Laḩij", type: "Governorate" },
  'YE-MA': { name: "Ma'rib", type: "Governorate" },
  'YE-MR': { name: "Al Mahrah", type: "Governorate" },
  'YE-MW': { name: "Al Maḩwīt", type: "Governorate" },
  'YE-RA': { name: "Raymah", type: "Governorate" },
  'YE-SA': { name: "Amānat al ‘Āşimah", type: "Municipality" },
  'YE-SD': { name: "Şāʻdah", type: "Governorate" },
  'YE-SH': { name: "Shabwah", type: "Governorate" },
  'YE-SN': { name: "Şanʻā'", type: "Governorate" },
  'YE-TA': { name: "Tāʻizz", type: "Governorate" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
