// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'YT';
export const countryName = "Mayotte";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'YT-YT': { name: "Mayotte", type: "Country" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
