// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'ZA';
export const countryName = "South Africa";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'ZA-EC': { name: "Eastern Cape", type: "Province" },
  'ZA-FS': { name: "Foreisetata", type: "Province" },
  'ZA-GT': { name: "Gauteng", type: "Province" },
  'ZA-LP': { name: "Limpopo", type: "Province" },
  'ZA-MP': { name: "iMpumalanga", type: "Province" },
  'ZA-NC': { name: "iTlhagwini-Kapa", type: "Province" },
  'ZA-NL': { name: "GaZulu-Natala", type: "Province" },
  'ZA-NW': { name: "Bokone Bophirima", type: "Province" },
  'ZA-WC': { name: "iTjhingalanga-Kapa", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
