// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'ZM';
export const countryName = "Zambia";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'ZM-01': { name: "Western", type: "Province" },
  'ZM-02': { name: "Central", type: "Province" },
  'ZM-03': { name: "Eastern", type: "Province" },
  'ZM-04': { name: "Luapula", type: "Province" },
  'ZM-05': { name: "Northern", type: "Province" },
  'ZM-06': { name: "North-Western", type: "Province" },
  'ZM-07': { name: "Southern", type: "Province" },
  'ZM-08': { name: "Copperbelt", type: "Province" },
  'ZM-09': { name: "Lusaka", type: "Province" },
  'ZM-10': { name: "Muchinga", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
