// Auto-generated by scripts/generate.ts - DO NOT EDIT
import type { SubdivisionInfo } from '../../types';
import { register } from '../registry';

export const countryCode = 'ZW';
export const countryName = "Zimbabwe";

export const subdivisions: Record<string, SubdivisionInfo> = {
  'ZW-BU': { name: "Bulawayo", type: "Province" },
  'ZW-HA': { name: "Harare", type: "Province" },
  'ZW-MA': { name: "Manicaland", type: "Province" },
  'ZW-MC': { name: "Mashonaland Central", type: "Province" },
  'ZW-ME': { name: "Mashonaland East", type: "Province" },
  'ZW-MI': { name: "Midlands", type: "Province" },
  'ZW-MN': { name: "Matabeleland North", type: "Province" },
  'ZW-MS': { name: "Matabeleland South", type: "Province" },
  'ZW-MV': { name: "Masvingo", type: "Province" },
  'ZW-MW': { name: "Mashonaland West", type: "Province" },
};

// Auto-register on import
register(countryCode, countryName, subdivisions);
