name: Deploy production

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'

env:
  VERCEL_ORG_ID: team_XfLFiZjBzWGeFIoVP1sV2ZXs
  VERCEL_PROJECT_ID: prj_qrxWqEgGGXNBTiLvWHbWqeqokyeu

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      repository-projects: write
      statuses: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: rkalkani/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ env.VERCEL_ORG_ID }}
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID }}
          working-directory: website
          scope: copperx-hq
          github-comment: false
          github-deployment: false
